/**
 * P4 decision-ledger migration contract.
 *
 * Exactly one P4 decision migration may exist, it must be additive and
 * append-only, it must not introduce a unique(cluster_id) overwrite key, and it
 * must be service-role-only. The executor's insert columns are cross-checked
 * against the migration so the ledger can never drift from the code.
 */

import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const MIGRATIONS_DIR = join(ROOT, 'supabase/migrations')

const migrationFiles = readdirSync(MIGRATIONS_DIR).filter((name) => /p4_cannibal_decisions/i.test(name))
const migrationSql = migrationFiles.length
  ? readFileSync(join(MIGRATIONS_DIR, migrationFiles[0]), 'utf8')
  : ''
const executorSource = readFileSync(join(ROOT, 'lib/seoFactory/cannibalMerge.ts'), 'utf8')

describe('P4 decision-ledger migration', () => {
  it('ships exactly one non-empty P4 decision migration (no competing duplicates)', () => {
    expect(migrationFiles).toHaveLength(1)
    expect(migrationSql.trim().length).toBeGreaterThan(0)
  })

  it('creates an additive append-only ledger table', () => {
    expect(migrationSql).toContain('create table if not exists public.seo_cannibal_decisions')
    expect(migrationSql).not.toMatch(/drop table/i)
    expect(migrationSql).toMatch(/before update or delete on public\.seo_cannibal_decisions/)
    expect(migrationSql).toMatch(/raise exception 'seo_cannibal_decisions is append-only/)
    expect(migrationSql).toContain('bigint generated by default as identity')
  })

  it('has no unique(cluster_id) overwrite behavior', () => {
    // Comments legitimately explain the absence of a unique key, so the
    // "no overwrite" assertions run against executable SQL only.
    const sql = migrationSql.replace(/--[^\n]*/g, '')
    expect(sql).not.toMatch(/unique/i)
    expect(sql).not.toMatch(/on conflict/i)
  })

  it('is service-role only behind RLS', () => {
    expect(migrationSql).toContain('enable row level security')
    expect(migrationSql).toMatch(/create policy "Service role full access" on public\.seo_cannibal_decisions/)
    expect(migrationSql).toMatch(/revoke all privileges on table public\.seo_cannibal_decisions from public, anon, authenticated/)
    expect(migrationSql).toMatch(/grant all privileges on table public\.seo_cannibal_decisions to service_role/)
  })

  it('supports every status and evidence source the executor persists', () => {
    expect(migrationSql).toMatch(/status in \('approved','executing','pr_opened','rejected','failed','superseded'\)/)
    expect(migrationSql).toMatch(/evidence_source in \('gsc_live','persisted_qualified_gsc'\)/)
  })

  it('declares every column the executor inserts', () => {
    const insertBlock = executorSource.slice(
      executorSource.indexOf("from('seo_cannibal_decisions')"),
      executorSource.indexOf('} as never)'),
    )
    expect(insertBlock.length).toBeGreaterThan(0)
    const columns = [...insertBlock.matchAll(/^\s{6}([a-z_]+)\s*[,:]/gm)].map((match) => match[1])
    expect(columns).toEqual(
      expect.arrayContaining([
        'cluster_id', 'term', 'status', 'evidence_source', 'evidence_hash', 'evidence_window',
        'evidence', 'competitors', 'winner_url', 'owner_registry_row_id', 'loser_actions',
        'rollback', 'decided_by', 'decided_at', 'pr_url', 'pr_number',
      ]),
    )
    for (const column of columns) {
      expect(migrationSql).toMatch(new RegExp(`^\\s*${column} `, 'm'))
    }
  })
})
