/**
 * P5 supervisor repair — site-health mutation protection regressions.
 *
 * BLOCKER 1: the mutation layer must protect the FULL registry by default, so a
 * repo-wide / delegated repair triggered by an unrelated batch can never touch a
 * registered KEEP_BUT_SILO URL. Caller-supplied URLs may only add to the set.
 *
 * BLOCKER 2: `repairSiteHealthChunked` — the live mutating path used by
 * `app/api/content-studio/site-health/route.ts` and `siteHealthComplete.ts` —
 * must refuse to inject a protected cohort URL as an orphan/internal-link
 * target or use it as the rewritten repair hub, while unregistered URLs behave
 * exactly as before.
 *
 * SAFETY: protection means "do not alter current state" — a protected URL
 * already listed in a studio sitemap keeps its entry; protection never removes
 * it and never adds a protected URL that was absent.
 */
import { Buffer } from 'node:buffer'
import { p5MutationVerdict, p5ProtectedUrlKeys } from '@/lib/seoFactory/p5OffMissionDispositions'
import { repairSiteHealth, repairSiteHealthChunked } from '@/lib/seoFactory/siteHealth'
import { fixNoIndexPagesChunked, hasNoIndexFlag } from '@/lib/seoFactory/siteHealthFixes'

const CASE = 'caseworks'
const HOST = 'https://legal.yousafeconsultancy.com'

/** Registered cohort URLs used by these fixtures (real registry entries). */
const UTAH_PATH = 'app/guide/university-of-utah-student-housing/page.tsx'
const UTAH_URL = `${HOST}/guide/university-of-utah-student-housing/`
const HOWARD_PATH = 'app/guide/howard-university-student-housing/page.tsx'
const HOWARD_URL = `${HOST}/guide/howard-university-student-housing/`
/** Unregistered URL — the P5 registry never names it. */
const PLAIN_PATH = 'app/us/student-visas/x/page.tsx'
const PLAIN_URL = `${HOST}/us/student-visas/x/`
const HUB_PATH = 'app/us/page.tsx'
const SITEMAP_PATH = 'app/sitemap.xml/route.ts'

const FILE_CONTENT: Record<string, string> = {
  [UTAH_PATH]: 'export const metadata = { title: "University of Utah student housing" }\n\nexport default function Page() {\n  return <main>Utah page</main>\n}\n',
  [HOWARD_PATH]: 'export const metadata = { title: "Howard University student housing" }\n\nexport default function Page() {\n  return <main>Howard page</main>\n}\n',
  // Links to the hub so the hub itself is not an orphan; the page itself has no inbound links.
  [PLAIN_PATH]: `export const metadata = { title: "Repair target page" }\n\nexport default function Page() {\n  return <main><a href="${HOST}/us/">hub</a></main>\n}\n`,
  [HUB_PATH]: `export const metadata = { title: "Estate hub" }\n\nexport default function Page() {\n  return <main>Hub</main>\n}\n`,
  [SITEMAP_PATH]: [
    'const STATIC_ROUTES = []',
    '// SITEMAP_ORPHAN_FIX_START — generated by Content Studio',
    'const STUDIO_SITEMAP_ROUTES: ReadonlyArray<SitemapRoute> = [',
    '  {',
    '    "path": "/guide/university-of-utah-student-housing",',
    '    "changeFrequency": "monthly",',
    '    "priority": 0.55',
    '  }',
    ']',
    '// SITEMAP_ORPHAN_FIX_END',
    '',
    '// ── File-tree walker',
    'export default async function sitemap() {',
    '  return [...STATIC_ROUTES, ...STUDIO_SITEMAP_ROUTES, ...registryRoutes]',
    '}',
  ].join('\n'),
}

const shaFor = (path: string) => `sha-${path}`

const mockGithubFetch = jest.fn()
const mockPutRepoFile = jest.fn()
const mockOpenPullRequest = jest.fn()

jest.mock('@/lib/githubContents', () => ({
  githubFetch: (...args: unknown[]) => mockGithubFetch(...args),
  putRepoFile: (...args: unknown[]) => mockPutRepoFile(...args),
  openPullRequest: (...args: unknown[]) => mockOpenPullRequest(...args),
  getBranchHeadSha: jest.fn(async () => 'mainsha'),
  getRepoFileContent: jest.fn(),
}))

/** Deterministic GitHub boundary over a fixture map. */
const makeGithubFetchImpl = (files: Record<string, string>) =>
  async (endpoint: string, init?: { method?: string }) => {
    const url = String(endpoint)
    const tree = url.match(/^\/repos\/kylemwalkerpr-ship-it\/([^/]+)\/git\/trees\/main\?recursive=1$/)
    if (tree) {
      return {
        tree: tree[1] === CASE
          ? Object.keys(files).map((path) => ({ path, type: 'blob', sha: shaFor(path) }))
          : [],
      }
    }
    const blob = url.match(/\/git\/blobs\/(.+)$/)
    if (blob) {
      for (const [path, content] of Object.entries(files)) {
        if (shaFor(path) === blob[1]) return { content: Buffer.from(content, 'utf8').toString('base64') }
      }
      throw new Error('GitHub 404: blob not found')
    }
    const contents = url.match(/\/contents\/(.+?)\?ref=main$/)
    if (contents) {
      const content = files[contents[1]]
      if (content == null) throw new Error('GitHub 404: Not Found')
      return { content: Buffer.from(content, 'utf8').toString('base64'), sha: shaFor(contents[1]) }
    }
    if (init?.method === 'PUT' || init?.method === 'POST') return { ok: true }
    return {}
  }

/** Deterministic GitHub boundary over the caseworks fixtures above. */
const githubFetchImpl = makeGithubFetchImpl(FILE_CONTENT)

type WriteCall = { repo: string; path: string; content: string }
const writes = (): WriteCall[] => mockPutRepoFile.mock.calls.map(([arg]) => arg as WriteCall)

beforeEach(() => {
  mockGithubFetch.mockReset().mockImplementation(githubFetchImpl)
  mockPutRepoFile.mockReset().mockResolvedValue({ ok: true })
  mockOpenPullRequest.mockReset().mockResolvedValue({ number: 7, html_url: 'https://github.com/example/pull/7' })
})

describe('P5 site-health protection — registry-accurate fixtures', () => {
  it('uses real registry cohort URLs so the regressions cannot be vacuous', () => {
    // If these ever stop being registry entries, the protection tests below
    // would pass trivially rather than proving anything.
    expect(p5ProtectedUrlKeys()).toEqual(expect.arrayContaining([UTAH_URL, HOWARD_URL]))
    expect(p5ProtectedUrlKeys()).not.toContain(PLAIN_URL)
  })
})

describe('P5 site-health protection — full registry by default', () => {
  it('never injects a registered URL as an orphan link or sitemap addition when the caller passes nothing', async () => {
    await repairSiteHealth(CASE, false)

    const hubWrite = writes().find((call) => call.path === HUB_PATH)
    expect(hubWrite).toBeDefined()
    // The unregistered orphan is still repaired exactly as before…
    expect(hubWrite!.content).toContain(PLAIN_URL)
    // …and no registered cohort URL is used as a link target.
    expect(hubWrite!.content).not.toContain(UTAH_URL)
    expect(hubWrite!.content).not.toContain(HOWARD_URL)

    // Retention, not removal: Utah was already in the studio sitemap block.
    const sitemapWrite = writes().find((call) => call.path === SITEMAP_PATH)
    expect(sitemapWrite).toBeDefined()
    expect(sitemapWrite!.content).toContain('/guide/university-of-utah-student-housing')
    // Never added: Howard was absent, so protection must not force it in.
    expect(sitemapWrite!.content).not.toContain('/guide/howard-university-student-housing')
    // The unregistered page is still synced (unchanged behavior).
    expect(sitemapWrite!.content).toContain('/us/student-visas/x')
  })

  it('cannot be narrowed by a caller list that omits every registry URL', async () => {
    await repairSiteHealth(CASE, false, { protectedUrls: ['https://example.com/not-ours/'] })

    const hubWrite = writes().find((call) => call.path === HUB_PATH)
    expect(hubWrite).toBeDefined()
    expect(hubWrite!.content).not.toContain(UTAH_URL)
    expect(hubWrite!.content).not.toContain(HOWARD_URL)
    const sitemapWrite = writes().find((call) => call.path === SITEMAP_PATH)
    expect(sitemapWrite!.content).not.toContain('/guide/howard-university-student-housing')
  })
})

describe('P5 site-health protection — chunked/complete mutation path', () => {
  it('skips protected cohort orphans but repairs unregistered ones', async () => {
    const result = await repairSiteHealthChunked(CASE, 0, 10, false)

    expect(result.protectedOrphansSkipped).toBe(2)
    expect(result.orphansFixed).toBe(1)
    // Exact outcome list: only the unregistered orphan was actually repaired.
    expect(result.fixedOrphans.map((o) => o.url)).toEqual([PLAIN_URL])
    expect(result.fixedOrphans.map((o) => o.repo)).toEqual([CASE])
    expect(result.nextBatch).toBeNull()

    const hubWrite = writes().find((call) => call.path === HUB_PATH)
    expect(hubWrite).toBeDefined()
    expect(hubWrite!.content).toContain(PLAIN_URL)
    expect(hubWrite!.content).not.toContain(UTAH_URL)
    expect(hubWrite!.content).not.toContain(HOWARD_URL)
    for (const call of writes()) {
      expect(call.content).not.toContain('university-of-utah-student-housing')
      expect(call.content).not.toContain('howard-university-student-housing')
    }
  })

  it('unions caller-supplied URLs in and stops when nothing repairable remains', async () => {
    const result = await repairSiteHealthChunked(CASE, 0, 10, false, { protectedUrls: [PLAIN_URL] })

    expect(result.protectedOrphansSkipped).toBe(3)
    expect(result.orphansFixed).toBe(0)
    expect(result.fixedOrphans).toEqual([])
    expect(result.repaired).toEqual([])
    expect(result.nextBatch).toBeNull()
    expect(mockPutRepoFile).not.toHaveBeenCalled()
    expect(mockOpenPullRequest).not.toHaveBeenCalled()
  })

  it('still repairs the unregistered cohort-free path when nothing is protected in the batch', async () => {
    const result = await repairSiteHealthChunked(CASE, 0, 10, true)
    expect(result.protectedOrphansSkipped).toBe(2)
    expect(result.orphansFixed).toBe(1)
    expect(result.fixedOrphans.map((o) => o.url)).toEqual([PLAIN_URL])
  })

  it('advances the batch cursor through repairable orphans it cannot repair (no usable hub)', async () => {
    // Same cohorts, but no repair-hub file exists, so nothing is repairable.
    // The cursor must still advance past every repairable candidate instead of
    // getting stuck on an unrepaired batch.
    const PLAIN_B_PATH = 'app/us/student-visas/y/page.tsx'
    const filesWithoutHub: Record<string, string> = { ...FILE_CONTENT }
    delete filesWithoutHub[HUB_PATH]
    filesWithoutHub[PLAIN_B_PATH] = 'export const metadata = { title: "Second repair target" }\n\nexport default function Page() {\n  return <main>Second target</main>\n}\n'
    mockGithubFetch.mockImplementation(makeGithubFetchImpl(filesWithoutHub))

    const first = await repairSiteHealthChunked(CASE, 0, 1, false)
    expect(first.orphansFixed).toBe(0)
    expect(first.fixedOrphans).toEqual([])
    expect(first.protectedOrphansSkipped).toBe(2)
    expect(first.nextBatch).toBe(1)

    const second = await repairSiteHealthChunked(CASE, 1, 1, false)
    expect(second.orphansFixed).toBe(0)
    expect(second.fixedOrphans).toEqual([])
    expect(second.nextBatch).toBeNull()

    expect(mockPutRepoFile).not.toHaveBeenCalled()
    expect(mockOpenPullRequest).not.toHaveBeenCalled()
  })
})

/**
 * BLOCKER 3 (final supervisor repair): the noindex mutation boundary itself —
 * `fixNoIndexPagesChunked()` — must consult the P5 disposition contract before
 * any read/write/branch/PR/history write for every candidate URL. A registered
 * KEEP_BUT_SILO candidate is skipped in place: it is never returned as fixed,
 * never rewritten, and never reaches a PR or the fix history. Unregistered
 * candidates keep the pre-P5 fix path exactly.
 */
const PLAIN_CONTENT_PATH = 'content/guides/plain-student-guide.mdx'
const PLAIN_CONTENT_URL = 'https://yousafeconsultancy.com/guides/plain-student-guide/'

const NOINDEX_FILES: Record<string, string> = {
  // Registered KEEP_BUT_SILO cohort page, carrying a real noindex directive.
  [UTAH_PATH]: [
    'export const metadata = { title: "University of Utah student housing", robots: "noindex, nofollow" }',
    '',
    'export default function Page() {',
    `  return <main>${'Utah student housing guide. '.repeat(60)}</main>`,
    '}',
    '',
  ].join('\n'),
  // Unregistered fully-expanded content page with front-matter index: false.
  [PLAIN_CONTENT_PATH]: [
    '---',
    'title: Plain student guide',
    'slug: /guides/plain-student-guide',
    'index: false',
    '---',
    '',
    `${'Plain student guide body. '.repeat(60)}`,
    '',
  ].join('\n'),
}

const protectedNoIndexCandidate = {
  repo: 'caseworks' as const,
  path: UTAH_PATH,
  url: UTAH_URL,
  title: 'University of Utah student housing',
  words: 500,
}
const plainNoIndexCandidate = {
  repo: 'yousafe-consultancy' as const,
  path: PLAIN_CONTENT_PATH,
  url: PLAIN_CONTENT_URL,
  title: 'Plain student guide',
  words: 500,
}

/** Decoded entries of the fix-history PUT, or null when no history write happened. */
const historyPutEntries = (): Array<Record<string, unknown>> | null => {
  const call = mockGithubFetch.mock.calls.find(
    ([endpoint, init]) =>
      String(endpoint).includes('.content-studio/site-health-fixes.json') &&
      (init as { method?: string } | undefined)?.method === 'PUT',
  )
  if (!call) return null
  const body = JSON.parse(String((call[1] as { body?: string }).body))
  return JSON.parse(Buffer.from(String(body.content), 'base64').toString('utf8'))
}

describe('P5 noindex mutation boundary — protected candidates are skipped before any write', () => {
  it('uses real registry URLs and real noindex content so the regressions cannot be vacuous', () => {
    expect(p5MutationVerdict(UTAH_URL)).toMatchObject({
      registered: true,
      disposition: 'KEEP_BUT_SILO',
      blocked: true,
    })
    expect(p5MutationVerdict(PLAIN_CONTENT_URL).blocked).toBe(false)
    expect(hasNoIndexFlag(NOINDEX_FILES[UTAH_PATH])).toBe(true)
    expect(hasNoIndexFlag(NOINDEX_FILES[PLAIN_CONTENT_PATH])).toBe(true)
  })

  it('does not read, rewrite, branch, PR or log a registered KEEP_BUT_SILO noindex candidate', async () => {
    mockGithubFetch.mockImplementation(makeGithubFetchImpl(NOINDEX_FILES))

    for (const dryRun of [false, true]) {
      const result = await fixNoIndexPagesChunked('caseworks', 0, 10, [protectedNoIndexCandidate], dryRun)

      expect(result.fixed).toEqual([])
      expect(result.skipped).toEqual([])
      expect(result.protectedSkipped).toHaveLength(1)
      expect(result.protectedSkipped[0]).toMatchObject({
        repo: 'caseworks',
        path: UTAH_PATH,
        url: UTAH_URL,
        disposition: 'KEEP_BUT_SILO',
      })
      expect(result.protectedSkipped[0].reason).toContain('KEEP_BUT_SILO')
      expect(result.totalCandidates).toBe(1)
      expect(result.nextBatch).toBeNull()
    }

    // The guard runs before even the contents read, so nothing touched GitHub.
    expect(mockGithubFetch).not.toHaveBeenCalled()
    expect(mockPutRepoFile).not.toHaveBeenCalled()
    expect(mockOpenPullRequest).not.toHaveBeenCalled()
  })

  it('still fixes an unregistered fully-expanded noindex candidate through the existing path', async () => {
    mockGithubFetch.mockImplementation(makeGithubFetchImpl(NOINDEX_FILES))

    const result = await fixNoIndexPagesChunked('yousafe-consultancy', 0, 10, [plainNoIndexCandidate], false)

    expect(result.protectedSkipped).toEqual([])
    expect(result.fixed).toEqual([
      {
        repo: 'yousafe-consultancy',
        path: PLAIN_CONTENT_PATH,
        url: PLAIN_CONTENT_URL,
        title: 'Plain student guide',
      },
    ])
    const write = writes().find((call) => call.path === PLAIN_CONTENT_PATH)
    expect(write).toBeDefined()
    expect(write!.content).toContain('index: true')
    expect(write!.content).not.toContain('index: false')
    expect(mockOpenPullRequest).toHaveBeenCalledTimes(1)

    const entries = historyPutEntries()
    expect(entries).toHaveLength(1)
    expect(entries![0]).toMatchObject({
      action: 'noindex',
      repo: 'yousafe-consultancy',
      path: PLAIN_CONTENT_PATH,
      url: PLAIN_CONTENT_URL,
    })
  })

  it('skips the protected candidate inside a mixed batch and never logs it as fixed', async () => {
    mockGithubFetch.mockImplementation(makeGithubFetchImpl(NOINDEX_FILES))

    const result = await fixNoIndexPagesChunked(
      'all',
      0,
      10,
      [protectedNoIndexCandidate, plainNoIndexCandidate],
      false,
    )

    expect(result.fixed.map((f) => f.path)).toEqual([PLAIN_CONTENT_PATH])
    expect(result.protectedSkipped.map((s) => s.path)).toEqual([UTAH_PATH])
    expect(result.skipped).toEqual([])
    expect(writes().map((call) => call.path)).toEqual([PLAIN_CONTENT_PATH])

    const prBody = String((mockOpenPullRequest.mock.calls[0][0] as { body?: string }).body)
    expect(prBody).toContain(PLAIN_CONTENT_PATH)
    expect(prBody).not.toContain(UTAH_PATH)
    expect(prBody).not.toContain('university-of-utah-student-housing')

    const entries = historyPutEntries()
    expect(entries).toHaveLength(1)
    expect(JSON.stringify(entries)).not.toContain(UTAH_URL)
    expect(JSON.stringify(entries)).not.toContain('university-of-utah-student-housing')
  })
})
