import { publicPathFromRepoFile, sitemapPathForShippedFile, upsertStudioSitemapEntry, normalizeStudioSitemapPath } from '@/lib/seoFactory/siteHealth'

describe('studio sitemap upsert', () => {
  const base = `export const dynamic = 'force-static'
const STATIC_ROUTES = []
// ── File-tree walker
function walk() {}
`

  it('sends each ship to the sitemap for that host, not usa by default', () => {
    expect(sitemapPathForShippedFile('yousafe-consultancy', 'landing-page/app/blog/h-1b-cap-exempt-employers/page.tsx'))
      .toBe('landing-page/app/sitemap.xml/route.ts')
    expect(sitemapPathForShippedFile('yousafe-consultancy', 'usa/content/from/nigeria.md'))
      .toBe('usa/app/sitemap.xml/route.ts')
    expect(sitemapPathForShippedFile('yousafe-consultancy', 'uk/content/blog/graduate-route.md'))
      .toBe('uk/app/sitemap.xml/route.ts')
    expect(sitemapPathForShippedFile('caseworks', 'app/us/f-1-opt/page.tsx'))
      .toBe('app/sitemap.xml/route.ts')
    expect(sitemapPathForShippedFile('portal', 'catalogue/foo.mdx'))
      .toBe('app/sitemap.ts')
  })

  it('converts a shipped page.tsx path into a public URL', () => {
    expect(publicPathFromRepoFile('app/us/education-verification/page.tsx')).toBe('/us/education-verification/')
  })

  it('maps regional content shards to live public paths (no content/ or .md)', () => {
    expect(publicPathFromRepoFile('ca/content/canada-express-entry-crs-international-student-graduates.md'))
      .toBe('/canada-express-entry-crs-international-student-graduates/')
    expect(publicPathFromRepoFile('uk/content/universities/uk-student-visa-process-for-warwick-university.md'))
      .toBe('/universities/uk-student-visa-process-for-warwick-university/')
    expect(publicPathFromRepoFile('usa/content/from/nigeria.md')).toBe('/from/nigeria/')
    expect(publicPathFromRepoFile('landing-page/content/blog/foo.md')).toBe('/blog/foo/')
    expect(normalizeStudioSitemapPath('/uk/content/universities/foo.md/'))
      .toBe('/universities/foo/')
  })

  it('inserts a 100% gate page into the studio sitemap block', () => {
    const first = upsertStudioSitemapEntry(base, 'app/us/education-verification/page.tsx', 'caseworks')
    expect(first.added).toBe(true)
    expect(first.content).toContain('/us/education-verification/')
    expect(first.content).toContain('STUDIO_SITEMAP_ROUTES')
    const second = upsertStudioSitemapEntry(first.content, '/us/education-verification/', 'caseworks')
    expect(second.added).toBe(false)
  })

  it('sanitizes legacy junk studio sitemap paths on upsert', () => {
    const dirty = `export const dynamic = 'force-static'
const STATIC_ROUTES = []
// SITEMAP_ORPHAN_FIX_START — generated by Content Studio
const STUDIO_SITEMAP_ROUTES: ReadonlyArray<{ path: string; priority: number; changefreq: string }> = [
  {
    "path": "/uk/content/universities/uk-student-visa-process-for-warwick-university.md/",
    "priority": 0.75,
    "changefreq": "weekly"
  }
]
// SITEMAP_ORPHAN_FIX_END
function escapeXml() {}
`
    const next = upsertStudioSitemapEntry(dirty, 'uk/content/from/student-tenant-rights-london-international-students.md', 'regional')
    expect(next.content).toContain('/universities/uk-student-visa-process-for-warwick-university/')
    expect(next.content).toContain('/from/student-tenant-rights-london-international-students/')
    expect(next.content).not.toContain('.md')
    expect(next.content).not.toContain('/uk/content/')
  })
})
