// data.jsx — Article/author/topic data pulled from the Caseworks codebase.

const TOPICS = [
  { slug: 'student-visas',  label: 'Student Visas',  region: 'US' },
  { slug: 'tenancy',        label: 'UK Tenancy',     region: 'UK' },
  { slug: 'immigration',    label: 'Immigration',    region: 'US' },
  { slug: 'express-entry',  label: 'Express Entry',  region: 'CA' },
  { slug: 'family',         label: 'Family & Spouse',region: 'CROSS' },
  { slug: 'opt-cpt',        label: 'OPT & CPT',      region: 'US' },
  { slug: 'compare',        label: 'Compare',        region: 'CROSS' },
];

const AUTHORS = {
  'maya-iyer': {
    id: 'maya-iyer',
    name: 'Maya Iyer',
    role: 'Immigration Attorney',
    firm: 'Riverbend Immigration Law, PLLC',
    location: 'Brooklyn, NY',
    bar: 'NY Bar #5482910',
    bio: 'Maya advises international students and early-career professionals on US student and work visas. She writes about the small filing decisions that quietly decide a case.',
    initials: 'MI',
    accent: 'oklch(60% 0.13 35)',
    following: 12_400,
    articles: 47,
  },
  'priya-chowdhury': {
    id: 'priya-chowdhury',
    name: 'Priya Chowdhury',
    role: 'Solicitor (England & Wales)',
    firm: 'Bracewell Tenant Solicitors',
    location: 'London, UK',
    bar: 'SRA 845112',
    bio: 'Tenancy specialist. Writing through the 2026 reforms one clause at a time.',
    initials: 'PC',
    accent: 'oklch(55% 0.13 200)',
    following: 8_910,
    articles: 31,
  },
  'noah-tremblay': {
    id: 'noah-tremblay',
    name: 'Noah Tremblay',
    role: 'Regulated Canadian Immigration Consultant',
    firm: 'Northshore RCIC',
    location: 'Toronto, ON',
    bar: 'R513889',
    bio: 'Express Entry, PGWP, and study permit refusals. Canadian application paperwork is a craft.',
    initials: 'NT',
    accent: 'oklch(50% 0.13 145)',
    following: 6_220,
    articles: 28,
  },
  'samira-okafor': {
    id: 'samira-okafor',
    name: 'Samira Okafor',
    role: 'Senior Editor',
    firm: 'Caseworks Editorial',
    location: 'New York, NY',
    bar: '',
    bio: 'Senior editor. Former immigration reporter at a national daily. Edits the Compare desk.',
    initials: 'SO',
    accent: 'oklch(50% 0.13 290)',
    following: 4_180,
    articles: 64,
  },
};

const AUTHOR_LIST = Object.values(AUTHORS);

// Article titles & topic mapping ripped from the codebase. Excerpts & body are
// original prose written in the publication voice.
const ARTICLES = [
  {
    id: 'i765-eight-mistakes',
    title: "Form I-765 OPT application: the eight common mistakes that get it denied",
    subtitle: "An attorney's read on the small filing decisions that quietly decide a case.",
    excerpt: "USCIS doesn't reject most OPT applications for grand reasons. It rejects them for the box you ticked on page two and the dated photograph you didn't crop.",
    author: 'maya-iyer',
    topic: 'opt-cpt',
    country: 'US',
    date: 'May 14, 2026',
    readingMinutes: 12,
    words: 2880,
    claps: 1284,
    responses: 47,
    isMember: false,
    hero: 'pull',  // 'pull' (no hero), 'image' (placeholder), 'frame'
    heroLabel: 'photograph — desk, stamped envelope, ink pen',
  },
  {
    id: 'f1-document-checklist-2026',
    title: 'The F-1 visa document checklist for 2026',
    subtitle: 'Every form, photograph, fee, and translation, in the order an officer will ask for them.',
    excerpt: 'A consular interview is a five-minute conversation that runs on the documents you brought. Bring the right ones in the right order and the conversation gets shorter.',
    author: 'maya-iyer',
    topic: 'student-visas',
    country: 'US',
    date: 'May 8, 2026',
    readingMinutes: 9,
    words: 2105,
    claps: 2_412,
    responses: 88,
    isMember: true,
    hero: 'image',
    heroLabel: 'flat-lay — passport, I-20, photographs, money order',
  },
  {
    id: 'renters-rights-act-students',
    title: "UK Renters' Rights Act 2025: a guide for international students",
    subtitle: 'The Act becomes the regime by May. Here is what changes for student tenancies in plain English.',
    excerpt: 'Periodic tenancies replace fixed terms by default. Section 21 is gone. Rent increases run on a single statutory route. None of that is theoretical anymore.',
    author: 'priya-chowdhury',
    topic: 'tenancy',
    country: 'UK',
    date: 'May 11, 2026',
    readingMinutes: 14,
    words: 3320,
    claps: 1_815,
    responses: 102,
    isMember: false,
    hero: 'image',
    heroLabel: 'photograph — terraced houses, To Let signs',
  },
  {
    id: 'section-21-abolished',
    title: 'Section 21 has been abolished: what it means for students renting in the UK',
    subtitle: 'The "no-fault" route is closed. What replaces it is narrower, and noisier.',
    excerpt: 'Landlords will still seek possession. They will just have to say why, in writing, on a statutory ground.',
    author: 'priya-chowdhury',
    topic: 'tenancy',
    country: 'UK',
    date: 'Apr 29, 2026',
    readingMinutes: 8,
    words: 1820,
    claps: 904,
    responses: 24,
    isMember: false,
    hero: 'pull',
    heroLabel: '',
  },
  {
    id: 'opt-vs-pgwp',
    title: "OPT or PGWP: a working comparison for international students choosing a country",
    subtitle: 'On paper they look similar. In practice they shape your first job, your taxes, and your second visa.',
    excerpt: 'OPT is a USCIS authorisation tied to your degree level. PGWP is an open work permit tied to your program length. The difference matters from week one.',
    author: 'samira-okafor',
    topic: 'compare',
    country: 'CROSS',
    date: 'May 6, 2026',
    readingMinutes: 11,
    words: 2540,
    claps: 3_120,
    responses: 156,
    isMember: true,
    hero: 'frame',
    heroLabel: 'editorial illustration — two stamped passports overlapping',
  },
  {
    id: 'express-entry-crs-2026',
    title: 'Canada Express Entry CRS calculator walkthrough for 2026',
    subtitle: 'A clause-by-clause read on the points system as it stands after the spring updates.',
    excerpt: 'CRS is not a scoring tool. It is a ranking tool. Your number only matters relative to the cutoffs IRCC actually pulls.',
    author: 'noah-tremblay',
    topic: 'express-entry',
    country: 'CA',
    date: 'May 3, 2026',
    readingMinutes: 13,
    words: 3010,
    claps: 1_402,
    responses: 61,
    isMember: false,
    hero: 'image',
    heroLabel: 'photograph — Toronto skyline, dawn light',
  },
  {
    id: 'cpt-vs-opt',
    title: 'CPT vs OPT — which applies to you',
    subtitle: 'A short, decisive table and a longer answer for the edges.',
    excerpt: 'The honest answer is: usually CPT first, OPT after. The interesting questions are the ones where that order breaks.',
    author: 'maya-iyer',
    topic: 'opt-cpt',
    country: 'US',
    date: 'Apr 24, 2026',
    readingMinutes: 7,
    words: 1640,
    claps: 712,
    responses: 19,
    isMember: false,
    hero: 'pull',
    heroLabel: '',
  },
  {
    id: 'spouse-visa-financial',
    title: 'The UK spouse visa financial requirement in 2026: how to actually meet it',
    subtitle: 'The threshold, the categories, and the documents UKVI quietly expects under each one.',
    excerpt: "The £29,000 figure is the headline. The categories beneath it are the story. Most refusals are not 'not enough money' — they are 'wrong evidence for the route'.",
    author: 'priya-chowdhury',
    topic: 'family',
    country: 'UK',
    date: 'Apr 19, 2026',
    readingMinutes: 10,
    words: 2400,
    claps: 1_122,
    responses: 35,
    isMember: false,
    hero: 'frame',
    heroLabel: 'illustration — payslips fanned out',
  },
  {
    id: 'spousal-sponsorship-canada',
    title: 'Canada spousal sponsorship: the document checklist (2026)',
    subtitle: 'Inside and outside Canada. What IRCC asks for and how it differs between streams.',
    excerpt: 'Spousal sponsorship is two streams sharing one name. Choosing wrongly is the most expensive thing you can do in the first week.',
    author: 'noah-tremblay',
    topic: 'family',
    country: 'CA',
    date: 'Apr 15, 2026',
    readingMinutes: 9,
    words: 2180,
    claps: 668,
    responses: 17,
    isMember: false,
    hero: 'pull',
    heroLabel: '',
  },
  {
    id: 'deposit-dispute-letter',
    title: "Deposit dispute letters in the UK: a tenant's template and walkthrough (2026)",
    subtitle: 'A short, useable letter and the law it sits on top of.',
    excerpt: 'A deposit scheme will not adjudicate something it has not seen in writing. The letter is the case.',
    author: 'priya-chowdhury',
    topic: 'tenancy',
    country: 'UK',
    date: 'Apr 9, 2026',
    readingMinutes: 6,
    words: 1310,
    claps: 482,
    responses: 9,
    isMember: false,
    hero: 'pull',
    heroLabel: '',
  },
];

// Body content for the reader page — written in the publication voice.
const BODY_I765 = [
  { type: 'p', text: "There is a particular silence in an immigration practice the morning a denial letter arrives. The associate reads it twice. The paralegal pulls the file. Somewhere there is a box that was ticked the wrong way, or a date that drifted by a week, or a photograph that has the right person and the wrong background. The rest of the case was fine." },
  { type: 'p', text: "Most Form I-765 denials are not adjudicative. They are clerical. USCIS does not reject the idea of your Optional Practical Training; it rejects the application you sent in. That distinction is useful, because clerical errors are the ones you can prevent in an afternoon." },
  { type: 'h2', id: 'one-the-eligibility-category', text: 'One: the eligibility category' },
  { type: 'p', text: "The first place an officer looks on a Form I-765 is question 27 — the eligibility category. There are over seventy of them. The five that matter for most international students sit in (c)(3): pre-completion OPT, post-completion OPT, the STEM extension, the cap-gap extension, and the rare H-1B beneficiary case." },
  { type: 'p', text: "Selecting the wrong sub-letter is not a typo. It is a different application. (c)(3)(B) is post-completion. (c)(3)(A) is pre-completion. If you wrote the latter and meant the former, the rest of your evidence becomes irrelevant, because it is evidence for a category you did not apply under." },
  { type: 'blockquote', text: "USCIS will not 'translate' an application. It will adjudicate the one you filed." },
  { type: 'h2', id: 'two-the-photograph', text: 'Two: the photograph' },
  { type: 'p', text: "The Department of State specification is two inches by two inches, taken within the last thirty days, in colour, with a white or off-white background. None of those parameters are negotiable. The background especially: a faint shadow on a white wall is a denial waiting for a slow week." },
  { type: 'p', text: "Use a pharmacy passport service or, if you must use a phone, use a backdrop. Crop to the head-and-shoulders frame the spec describes. Write your name on the back in pencil, lightly enough not to indent the front." },
  { type: 'h2', id: 'three-the-i20-endorsement', text: 'Three: the I-20 endorsement' },
  { type: 'p', text: "Your Designated School Official must endorse the OPT request on page two of your I-20 within the thirty days before you file. If the endorsement is older than that, the form is not current. If it is newer than your filing window opens, the school filed too early." },
  { type: 'p', text: "An I-20 with no OPT endorsement is the single most common reason an OPT packet comes back. The remedy is short: ask your DSO for a fresh I-20 dated today. Do not file with the old one." },
  { type: 'h2', id: 'four-the-filing-window', text: 'Four: the filing window' },
  { type: 'p', text: "Post-completion OPT must be filed within ninety days before your program end date and up to sixty days after. Most students know the start of the window. Fewer know the end. A packet that arrives on day sixty-one is not late — it is unfileable." },
  { type: 'p', text: "Count from the end date that appears on your most recent I-20, not from your last final exam. Those are usually the same. They are not always." },
  { type: 'h2', id: 'five-the-fee', text: 'Five: the fee' },
  { type: 'p', text: "Pay by money order, personal cheque, or credit card through G-1450. Do not staple the cheque to the form. Do not write a single cheque covering multiple applications. Make the cheque out to 'U.S. Department of Homeland Security' — not 'USCIS', not 'DHS', not the abbreviation. Officers reject cheques made out to the abbreviation. They are allowed to." },
  { type: 'h2', id: 'six-the-signature', text: 'Six: the signature' },
  { type: 'p', text: "The signature must be in ink, on the line, by the applicant. Not the applicant's parent. Not the applicant's DSO. Not a scanned signature pasted into a PDF. If you electronically file through myUSCIS the platform handles this; if you file by mail, an unsigned application is rejected without adjudication." },
  { type: 'h2', id: 'seven-the-address', text: 'Seven: the address' },
  { type: 'p', text: "The address you list must be one where you will receive mail for ninety days. A summer dorm is not that. A friend's house in a city you are about to leave is not that. If your address is going to change, file a Form AR-11 immediately after filing the I-765 — and check the box that updates pending applications." },
  { type: 'h2', id: 'eight-the-supporting-evidence', text: 'Eight: the supporting evidence' },
  { type: 'p', text: "A clean I-765 ships with: the form itself, two passport photographs, a photocopy of your most recent I-94, a photocopy of your previous EAD if any, a photocopy of pages one through three of your most recent I-20, a photocopy of your passport biographic page, and the filing fee." },
  { type: 'p', text: "It does not ship with original documents, a personal statement, or a letter from your DSO unless one is specifically required for your category. The instinct to send more is the instinct to make the file harder for the officer to process. Resist it." },
  { type: 'h2', id: 'the-quiet-ninth', text: 'The quiet ninth' },
  { type: 'p', text: "There is a ninth mistake that is harder to name. It is the assumption that USCIS will figure it out. They will not. They will adjudicate what is in front of them, in the language the form uses, against the category you selected, on the evidence you provided. The job is not to convince an officer. The job is to give the officer a complete file." },
  { type: 'p', text: "When clients ask what to do the night before they file, I tell them the same thing every time: put the packet down and read it as if it had arrived in the mail. Read the boxes. Read the photograph. Read the signature line. The denial letters in my drawer all read like documents that were never read again after they were finished." },
];

const COMMENTS_I765 = [
  {
    id: 'c1',
    author: 'priya-chowdhury',
    date: '2 days ago',
    text: "The point about not sending originals is one most new lawyers ignore for the first six months. You ship clean files or you ship loud files; USCIS prefers clean.",
    claps: 38,
    replies: [
      {
        id: 'c1r1',
        author: 'maya-iyer',
        date: '1 day ago',
        text: "Half my edits to associate drafts are 'remove this'.",
        claps: 22,
      },
    ],
  },
  {
    id: 'c2',
    author: 'samira-okafor',
    date: '3 days ago',
    text: "We almost re-titled this 'eight clerical mistakes and one mindset' before publishing. The ninth is the one that actually gets you.",
    claps: 19,
    replies: [],
  },
  {
    id: 'c3',
    author: 'noah-tremblay',
    date: '5 days ago',
    text: "Canadian PGWP processing has the same energy — most refusals are document-completeness, not eligibility. The submitted package is the case.",
    claps: 14,
    replies: [],
  },
];

// Expose to other Babel files
Object.assign(window, {
  TOPICS, AUTHORS, AUTHOR_LIST, ARTICLES,
  BODY_I765, COMMENTS_I765,
});
