import type { PayhipBatches24Product } from './payhipBatches24Types'

export const PAYHIP_BATCH4_PRODUCTS: readonly PayhipBatches24Product[] = [
  {
    productNumber: 28,
    batch: 4,
    slug: '30-day-habit-wellness-tracker',
    apexSlug: 'shop-30-day-habit-wellness-tracker',
    payhipId: 'Jnm2E',
    legacyCardId: 'habit-tracker',
    name: '30-Day Habit & Wellness Tracker — Printable PDF',
    price: 7.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k287h1er124980s36i1vl3gt1f.jpg',
    imageAlt: 'Real person marking a habit tracker or wellness journal at a desk',
    description: 'An 8-page printable tracker for one habit at a time: setup page, 30-day completion/energy grid, four weekly reflection pages and a final 30-day review. It is a personal planning resource, not medical or mental-health treatment.',
    deliveryLabel: '8-page printable PDF',
    buyerFile: '30-day-habit-wellness-tracker.pdf',
    fileShopCategory: 'guide',
    tags: ['habit tracker', '30 day tracker', 'wellness tracker', 'printable habit tracker', 'goal tracker', 'weekly reflection', 'self improvement', 'PDF planner'],
    marketplaceCategory: 'Lifestyle / Productivity',
    authorityLinks: [],
    relatedSlugs: ['90-day-guided-self-reflection-journal', 'undated-hyperlinked-digital-planner'],
  },
  {
    productNumber: 29,
    batch: 4,
    slug: '50-ai-prompts-content-creators-marketers',
    apexSlug: 'shop-50-ai-prompts-content-creators-marketers',
    payhipId: 'ju1Xm',
    legacyCardId: 'ai-prompts-creators',
    name: '50 AI Prompts for Content Creators & Marketers — Practical Prompt Workbook PDF',
    price: 8.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k288l36pg4g1sddgb712v21alr1f.jpg',
    imageAlt: 'Real content creator working on laptop with notes, camera or phone nearby',
    description: 'Fifty structured prompts for strategy, hooks/scripts, SEO/research, email/conversion, repurposing and quality/analytics. Prompts include variables and constraints rather than vague one-line commands. Works with general-purpose AI assistants; buyer should verify factual and high-stakes outputs.',
    deliveryLabel: '11-page PDF · 50 prompts',
    buyerFile: '50-ai-prompts-content-creators-marketers.pdf',
    fileShopCategory: 'guide',
    tags: ['AI prompts', 'content creator prompts', 'marketing prompts', 'ChatGPT prompts', 'content strategy', 'social media prompts', 'SEO prompts', 'prompt workbook'],
    marketplaceCategory: 'Business / Marketing',
    authorityLinks: [],
    relatedSlugs: ['social-media-post-template-pack-8-editable-posts', 'content-calendar-social-media-planner'],
  },
  {
    productNumber: 30,
    batch: 4,
    slug: 'rental-property-income-expense-tracker',
    apexSlug: 'shop-rental-property-income-expense-tracker',
    payhipId: 'ROGvC',
    legacyCardId: 'rental-tracker',
    name: 'Rental Property Income & Expense Tracker — Excel & Google Sheets',
    price: 12.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k289gm2f1ijm1mhmerk1nr8a501f.jpg',
    imageAlt: 'Real landlord or property manager reviewing rental paperwork and laptop',
    description: 'A multi-sheet workbook for Properties, Transactions and automatic Property Summary roll-ups. Track rent targets, occupancy, income, expenses and net cash flow by Property ID. Designed for operational tracking, not tax filing or accounting advice.',
    deliveryLabel: 'Excel workbook, Google Sheets compatible',
    buyerFile: 'rental-property-income-expense-tracker.xlsx',
    fileShopCategory: 'spreadsheet',
    tags: ['rental property tracker', 'landlord spreadsheet', 'rental income', 'rental expenses', 'property cash flow', 'landlord bookkeeping', 'Excel template', 'Google Sheets'],
    marketplaceCategory: 'Business / Property',
    authorityLinks: [],
    relatedSlugs: ['household-budget-debt-payoff-tracker', 'solo-consultant-business-toolkit'],
  },
  {
    productNumber: 31,
    batch: 4,
    slug: 'content-calendar-social-media-planner',
    apexSlug: 'shop-content-calendar-social-media-planner',
    payhipId: 'xdCZl',
    legacyCardId: 'content-calendar',
    name: 'Content Calendar & Social Media Planner — Excel & Google Sheets',
    price: 10.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28d49ld19861f301mkv1ak41ebl1f.jpg',
    imageAlt: 'Real marketing planning desk with calendar, laptop and social content notes',
    description: 'A four-sheet planning system with Content Calendar, Idea Bank, Performance Log and Dashboard. Track publish dates, channels, formats, CTAs, workflow status and post-performance metrics. No platform API connection is included; metrics are entered by the buyer.',
    deliveryLabel: 'Excel workbook, Google Sheets compatible',
    buyerFile: 'content-calendar-social-media-planner.xlsx',
    fileShopCategory: 'spreadsheet',
    tags: ['content calendar', 'social media planner', 'marketing calendar', 'content planner spreadsheet', 'social media tracker', 'content ideas', 'performance tracker', 'Excel template'],
    marketplaceCategory: 'Business / Marketing',
    authorityLinks: [],
    relatedSlugs: ['social-media-post-template-pack-8-editable-posts', '50-ai-prompts-content-creators-marketers'],
  },
  {
    productNumber: 32,
    batch: 4,
    slug: 'wedding-budget-vendor-tracker',
    apexSlug: 'shop-wedding-budget-vendor-tracker',
    payhipId: 'tWBz2',
    legacyCardId: 'wedding-budget-planner',
    name: 'Wedding Budget Planner + Vendor Tracker — Excel & Google Sheets',
    price: 11.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28ear054v8jgj3v01oqbad21f.jpg',
    imageAlt: 'Real couple or planner reviewing wedding budget and vendor paperwork',
    description: 'A four-sheet workbook for Budget, Vendors, Payments and Dashboard. Compare budget, estimates, contracted amounts and paid amounts; track vendor quotes, deposits, balances and due dates; and see overall budget headroom.',
    deliveryLabel: 'Excel workbook, Google Sheets compatible',
    buyerFile: 'wedding-budget-vendor-tracker.xlsx',
    fileShopCategory: 'spreadsheet',
    tags: ['wedding budget', 'vendor tracker', 'wedding spreadsheet', 'wedding planner', 'deposit tracker', 'wedding expenses', 'Excel wedding planner', 'Google Sheets'],
    marketplaceCategory: 'Wedding / Events',
    authorityLinks: [],
    relatedSlugs: ['wedding-invitation-suite-editable-word', 'household-budget-debt-payoff-tracker'],
  },
  {
    productNumber: 33,
    batch: 4,
    slug: 'household-budget-debt-payoff-tracker',
    apexSlug: 'shop-household-budget-debt-payoff-tracker',
    payhipId: 'sjFIf',
    legacyCardId: 'budget-debt-planner',
    name: 'Household Budget Planner + Debt Payoff Tracker — Excel & Google Sheets',
    price: 10.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28f0qiv1rq414ui6qj1mgk1pm31f.jpg',
    imageAlt: 'Real household budgeting session with calculator, bills and notebook',
    description: 'Track monthly budget vs actual spending, current debts, APRs, payments and estimated payoff months, with a simple dashboard for income, expenses, net position and debt totals. Estimates are planning calculations, not financial advice or lender figures.',
    deliveryLabel: 'Excel workbook, Google Sheets compatible',
    buyerFile: 'household-budget-debt-payoff-tracker.xlsx',
    fileShopCategory: 'spreadsheet',
    tags: ['household budget', 'debt payoff tracker', 'monthly budget spreadsheet', 'personal finance template', 'debt tracker', 'budget planner', 'Excel budget', 'Google Sheets budget'],
    marketplaceCategory: 'Lifestyle / Finance',
    authorityLinks: [],
    relatedSlugs: ['freelance-rate-project-profitability-calculator', 'weekly-meal-planner-grocery-list'],
  },
  {
    productNumber: 34,
    batch: 4,
    slug: 'freelance-rate-project-profitability-calculator',
    apexSlug: 'shop-freelance-rate-project-profitability-calculator',
    payhipId: 'ZLyP9',
    legacyCardId: 'rate-calculator',
    name: 'Freelance Rate Calculator + Project Profitability Tracker — Excel & Google Sheets',
    price: 11.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28dar0817vjte9joumn1kc91f.jpg',
    imageAlt: 'Real freelancer reviewing project quote and calculator on laptop',
    description: 'Estimate a sustainable hourly/day rate from take-home income goal, overhead, tax reserve, working weeks, billable hours and profit/safety margin. Then compare quoted project revenue with delivery hours and direct costs. Planning tool only; tax and pricing decisions remain the buyer’s responsibility.',
    deliveryLabel: 'Excel workbook, Google Sheets compatible',
    buyerFile: 'freelance-rate-project-profitability-calculator.xlsx',
    fileShopCategory: 'spreadsheet',
    tags: ['freelance rate calculator', 'hourly rate calculator', 'project profitability', 'freelancer spreadsheet', 'pricing calculator', 'consultant rate', 'Excel calculator', 'Google Sheets'],
    marketplaceCategory: 'Business / Freelance',
    authorityLinks: [],
    relatedSlugs: ['solo-consultant-business-toolkit', 'client-welcome-packet-template'],
  },
  {
    productNumber: 35,
    batch: 4,
    slug: 'solo-consultant-business-toolkit',
    apexSlug: 'shop-solo-consultant-business-toolkit',
    payhipId: 'xQg6i',
    legacyCardId: 'consultant-toolkit',
    name: 'Solo Consultant Business Toolkit — Clients, Projects, Invoices & Cash Flow',
    price: 14.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28eekj61d6610eme3k44ugl11a.jpg',
    imageAlt: 'Real solo consultant at desk reviewing client work and business numbers',
    description: 'A six-sheet operating workbook for Clients, Projects, Invoices, Expenses, Cash Flow and Dashboard. Track client status, project fees and due dates, invoice/payment status, expenses, monthly cash movement and receivables in one lightweight system.',
    deliveryLabel: '6-sheet Excel workbook, Google Sheets compatible',
    buyerFile: 'solo-consultant-business-toolkit.xlsx',
    fileShopCategory: 'spreadsheet',
    tags: ['consultant toolkit', 'client tracker', 'invoice tracker', 'project tracker', 'cash flow spreadsheet', 'freelance business', 'consulting operations', 'Excel template'],
    marketplaceCategory: 'Business / Freelance',
    authorityLinks: [],
    relatedSlugs: ['freelance-rate-project-profitability-calculator', 'client-welcome-packet-template'],
  },
  {
    productNumber: 36,
    batch: 4,
    slug: '50-ai-prompts-small-business-owners',
    apexSlug: 'shop-50-ai-prompts-small-business-owners',
    payhipId: 'rlsyK',
    legacyCardId: 'ai-prompts-business',
    name: '50 AI Prompts for Small Business Owners — Strategy, Sales & Operations PDF',
    price: 8.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28g6kiq1v4g1tbs4q3154g10uj1a.jpg',
    imageAlt: 'Real small-business owner using laptop with planning notebook and business documents',
    description: 'Fifty structured prompts for strategy, sales, marketing, operations, finance, customer experience, delegation, product decisions, QA/risk and weekly review. Built around real business inputs and constraints rather than generic “act as an expert” commands. Verify factual and high-stakes outputs independently.',
    deliveryLabel: '11-page PDF · 50 prompts',
    buyerFile: '50-ai-prompts-small-business-owners.pdf',
    fileShopCategory: 'guide',
    tags: ['AI prompts business', 'small business prompts', 'ChatGPT business', 'sales prompts', 'marketing prompts', 'operations prompts', 'business strategy', 'prompt workbook'],
    marketplaceCategory: 'Business / Productivity',
    authorityLinks: [],
    relatedSlugs: ['small-business-startup-checklist-90-day-plan', 'solo-consultant-business-toolkit'],
  },
]
