import type { PayhipBatches24Product } from './payhipBatches24Types'

export const PAYHIP_BATCH3_PRODUCTS: readonly PayhipBatches24Product[] = [
  {
    productNumber: 19,
    batch: 3,
    slug: 'svg-cut-file-bundle-8-designs',
    apexSlug: 'shop-svg-cut-file-bundle-8-designs',
    payhipId: 'ntE4Q',
    legacyCardId: 'svg-bundle',
    name: 'SVG Cut File Bundle — 8 Clean Designs for Cricut & Silhouette',
    price: 6.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k287hn851mfp8ao15lq1nmh1g8r1a.jpg',
    imageAlt: 'Real craft cutting workspace with vinyl, cutting mat and craft machine, no fake finished product mockup',
    description: 'Eight clean, resizable SVG vector designs packaged in one ZIP: monogram circle, heart outline, leaf sprig, starburst, home icon, mountain badge, floral frame and arch frame. Valid SVG files with no raster image dependency. Buyer should still test cut settings for their own machine and material.',
    deliveryLabel: 'ZIP containing 8 SVG files',
    buyerFile: 'svg-cut-file-bundle-8-designs.zip',
    fileShopCategory: 'craft',
    tags: ['SVG bundle', 'Cricut SVG', 'Silhouette cut files', 'vector cut files', 'craft SVG', 'monogram SVG', 'cutting machine files', 'digital craft'],
    marketplaceCategory: 'Craft & Print',
    authorityLinks: [],
    relatedSlugs: ['minimalist-wall-art-bundle-6-prints', 'social-media-post-template-pack-8-editable-posts'],
  },
  {
    productNumber: 20,
    batch: 3,
    slug: 'minimalist-wall-art-bundle-6-prints',
    apexSlug: 'shop-minimalist-wall-art-bundle-6-prints',
    payhipId: 'XLI0e',
    legacyCardId: 'wall-art',
    name: 'Minimalist Wall Art Bundle — 6 Print-Ready 8×10 PDFs',
    price: 8.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k288ghv11ut0b0eolprv015ql1a.jpg',
    imageAlt: 'Real modern interior wall with neutral framed art, natural photography',
    description: 'Six coordinated minimalist 8×10 PDF prints in one ZIP, designed in a restrained navy, cream and gold visual system. Print at home or through a print shop. Frames are not included; final color can vary by printer, paper and display.',
    deliveryLabel: 'ZIP containing 6 print-ready PDF artworks',
    buyerFile: 'minimalist-wall-art-bundle-6-prints.zip',
    fileShopCategory: 'craft',
    tags: ['printable wall art', 'minimalist art', '8x10 prints', 'gallery wall', 'abstract print', 'instant download art', 'home decor printable', 'PDF wall art'],
    marketplaceCategory: 'Craft & Print',
    authorityLinks: [],
    relatedSlugs: ['svg-cut-file-bundle-8-designs', 'wedding-invitation-suite-editable-word'],
  },
  {
    productNumber: 21,
    batch: 3,
    slug: 'undated-hyperlinked-digital-planner',
    apexSlug: 'shop-undated-hyperlinked-digital-planner',
    payhipId: 'rRVb4',
    legacyCardId: 'digital-planner',
    name: 'Undated Hyperlinked Digital Planner — GoodNotes & Notability PDF',
    price: 12.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k289houdnkaou7ija1rbd1qm31a.jpg',
    imageAlt: 'Real tablet with stylus and digital planning screen on desk, natural lifestyle photography',
    description: 'A reusable 19-page hyperlinked PDF with clickable Year, Month, Week, Day, Habits and Notes navigation plus 12 reusable undated month pages. Designed for annotation apps that support PDF links. No proprietary app is included.',
    deliveryLabel: '19-page hyperlinked PDF',
    buyerFile: 'undated-hyperlinked-digital-planner.pdf',
    fileShopCategory: 'guide',
    tags: ['digital planner', 'GoodNotes planner', 'Notability planner', 'hyperlinked planner', 'undated planner', 'iPad planner', 'productivity PDF', 'digital planning'],
    marketplaceCategory: 'Lifestyle / Productivity',
    authorityLinks: [],
    relatedSlugs: ['30-day-habit-wellness-tracker', '90-day-guided-self-reflection-journal'],
  },
  {
    productNumber: 22,
    batch: 3,
    slug: 'social-media-post-template-pack-8-editable-posts',
    apexSlug: 'shop-social-media-post-template-pack-8-editable-posts',
    payhipId: '9jpJQ',
    legacyCardId: 'social-templates',
    name: 'Social Media Post Template Pack — 8 Editable Square PowerPoint Layouts',
    price: 11.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28aoq5s1dj6g7f1jj51gmk1c4p1a.jpg',
    imageAlt: 'Real marketer or small-business owner designing social posts on laptop, real desk photography',
    description: 'Eight editable 1:1 PowerPoint post layouts for quote, tip, sale, testimonial, how-to, statistic, announcement and carousel-cover content. Text and shapes remain editable. Export finished slides to PNG/JPG before posting.',
    deliveryLabel: 'PowerPoint · 8 editable square slides',
    buyerFile: 'social-media-post-template-pack-8-editable-posts.pptx',
    fileShopCategory: 'template',
    tags: ['social media templates', 'Instagram templates', 'PowerPoint social media', 'editable post templates', 'content creator templates', 'marketing templates', 'square post design', 'PPTX'],
    marketplaceCategory: 'Business / Marketing',
    authorityLinks: [],
    relatedSlugs: ['content-calendar-social-media-planner', '50-ai-prompts-content-creators-marketers'],
  },
  {
    productNumber: 23,
    batch: 3,
    slug: 'business-plan-investor-pitch-deck-template',
    apexSlug: 'shop-business-plan-investor-pitch-deck-template',
    payhipId: 'KX0Rd',
    legacyCardId: 'pitch-deck',
    name: 'Business Plan & Investor Pitch Deck Template — 10 Editable PowerPoint Slides',
    price: 14.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28ei5ina4kmeiomu5abbor1a.jpg',
    imageAlt: 'Real startup team reviewing pitch deck on laptop or presentation screen',
    description: 'A 10-slide editable PowerPoint structure covering company/value proposition, problem, solution, market, product, business model, traction, go-to-market, competition and team/ask. Includes editable content blocks and a traction chart. It does not provide financial or fundraising guarantees.',
    deliveryLabel: 'PowerPoint · 10 editable slides',
    buyerFile: 'business-plan-investor-pitch-deck-template.pptx',
    fileShopCategory: 'template',
    tags: ['pitch deck template', 'investor deck', 'business plan presentation', 'startup pitch', 'PowerPoint template', 'fundraising deck', 'editable pitch deck', 'startup presentation'],
    marketplaceCategory: 'Business / Startup',
    authorityLinks: [],
    relatedSlugs: ['small-business-startup-checklist-90-day-plan', 'solo-consultant-business-toolkit'],
  },
  {
    productNumber: 24,
    batch: 3,
    slug: 'client-welcome-packet-template',
    apexSlug: 'shop-client-welcome-packet-template',
    payhipId: 'YngNy',
    legacyCardId: 'welcome-packet',
    name: 'Client Welcome Packet Template — Editable Word Onboarding Document',
    price: 9.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28ge1e8etuospk5iehbifc1a.jpg',
    imageAlt: 'Real consultant meeting client with onboarding documents, professional desk setting',
    description: 'An editable Word onboarding packet covering welcome, project snapshot, communication, timeline and milestones, feedback/revisions, billing, access/assets, completion/handoff and contact details. Replace placeholders to match your contract and local requirements.',
    deliveryLabel: 'Editable DOCX',
    buyerFile: 'client-welcome-packet-template.docx',
    fileShopCategory: 'template',
    tags: ['client welcome packet', 'client onboarding', 'freelance template', 'consultant onboarding', 'Word template', 'project kickoff', 'client experience', 'editable DOCX'],
    marketplaceCategory: 'Business / Freelance',
    authorityLinks: [],
    relatedSlugs: ['solo-consultant-business-toolkit', 'freelance-rate-project-profitability-calculator'],
  },
  {
    productNumber: 25,
    batch: 3,
    slug: 'wedding-invitation-suite-editable-word',
    apexSlug: 'shop-wedding-invitation-suite-editable-word',
    payhipId: '9Pgn8',
    legacyCardId: 'wedding-stationery',
    name: 'Wedding Invitation Suite — 4 Editable Word Cards',
    price: 12.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k0pcsmdh1moesmb1ceijjk1gv615.jpg',
    imageAlt: 'Real elegant wedding stationery flat lay with invitation cards and flowers',
    description: 'A coordinated four-piece wedding stationery suite in editable Word format: invitation, RSVP card, details card and thank-you note. The purchased ZIP contains four separate DOCX files. Buyers should test print sizing and fonts on their own printer before ordering a full run.',
    deliveryLabel: 'ZIP containing 4 editable DOCX cards',
    buyerFile: 'wedding-invitation-suite-editable-word.zip',
    fileShopCategory: 'template',
    tags: ['wedding invitation', 'RSVP card', 'wedding details card', 'thank you card', 'editable wedding template', 'Word invitation', 'wedding stationery', 'DOCX'],
    marketplaceCategory: 'Wedding / Events',
    authorityLinks: [],
    relatedSlugs: ['wedding-budget-vendor-tracker', 'minimalist-wall-art-bundle-6-prints'],
  },
  {
    productNumber: 26,
    batch: 3,
    slug: 'ats-resume-matching-cover-letter-templates',
    apexSlug: 'shop-ats-resume-matching-cover-letter-templates',
    payhipId: 'eB2KM',
    legacyCardId: 'resume-template',
    name: 'ATS-Friendly Resume Template + Matching Cover Letter — Editable Word Files',
    price: 9.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28f461pqq115qgu3m1krk1c8815.jpg',
    imageAlt: 'Real job seeker editing resume on laptop with printed CV nearby',
    description: 'Two editable Word files: a clean single-column resume template and matching cover-letter framework. The design avoids text boxes, graphics and multi-column layouts that commonly complicate parsing. No template can guarantee ATS ranking or an interview; the buyer must replace every placeholder with truthful experience.',
    deliveryLabel: 'ZIP containing 2 editable DOCX files',
    buyerFile: 'ats-resume-matching-cover-letter-templates.zip',
    fileShopCategory: 'template',
    tags: ['ATS resume template', 'cover letter template', 'resume Word template', 'job application', 'professional resume', 'editable CV', 'career template', 'DOCX'],
    marketplaceCategory: 'Career / Job Search',
    authorityLinks: [],
    relatedSlugs: ['client-welcome-packet-template', 'small-business-startup-checklist-90-day-plan'],
  },
  {
    productNumber: 27,
    batch: 3,
    slug: 'small-business-startup-checklist-90-day-plan',
    apexSlug: 'shop-small-business-startup-checklist-90-day-plan',
    payhipId: 'yJP2Y',
    legacyCardId: 'startup-checklist',
    name: 'Small Business Startup Checklist + 90-Day Launch Plan — Printable PDF',
    price: 9.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k0pcr9h81ttb1116ntc1ndc31t15.jpg',
    imageAlt: 'Real small business owner planning launch with notebook and laptop',
    description: 'An 8-page practical launch guide covering problem validation, minimum offer, basic operations, days 1-30, 31-60 and 61-90, plus a 90-day scorecard. It is a planning resource, not legal, tax or accounting advice; local registration and compliance requirements must be checked separately.',
    deliveryLabel: '8-page PDF',
    buyerFile: 'small-business-startup-checklist-90-day-plan.pdf',
    fileShopCategory: 'guide',
    tags: ['startup checklist', '90 day business plan', 'small business launch', 'business startup guide', 'first customer plan', 'entrepreneur checklist', 'launch plan', 'PDF guide'],
    marketplaceCategory: 'Business / Startup',
    authorityLinks: [],
    relatedSlugs: ['business-plan-investor-pitch-deck-template', '50-ai-prompts-small-business-owners'],
  },
]
