import type { PayhipBatches24Product } from './payhipBatches24Types'

export const PAYHIP_BATCH2_PRODUCTS: readonly PayhipBatches24Product[] = [
  {
    productNumber: 10,
    batch: 2,
    slug: 'us-i134-financial-support-companion-pack',
    apexSlug: 'shop-us-i134-financial-support-companion-pack',
    payhipId: 'b3pSu',
    name: 'USA I-134 Financial Support Companion Pack — Fillable PDF',
    price: 12.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k287r7fh1robpduepp15f71s711f.jpg',
    imageAlt: 'Financial supporter reviewing bank statements and documents at a desk, real people, no fake USCIS forms',
    description: 'Organize sponsor identity, income, assets, relationship evidence, supporting documents and explanation notes before using the current USCIS I-134 process. The workbook is a preparation companion, not Form I-134 itself. It does not determine whether I-134 is required for a particular visa or benefit and does not guarantee acceptance. Always use the current USCIS form and instructions.',
    deliveryLabel: '1 fillable PDF workbook',
    buyerFile: 'us-i134-financial-support-companion-pack.pdf',
    fileShopCategory: 'template',
    tags: ['I-134', 'financial support', 'US visa support', 'sponsor evidence', 'USCIS preparation', 'financial document organizer', 'fillable PDF', 'immigration preparation'],
    marketplaceCategory: 'Education',
    authorityLinks: [{ label: 'Form I-134, Declaration of Financial Support — USCIS', href: 'https://www.uscis.gov/i-134' }, { label: 'All USCIS forms', href: 'https://www.uscis.gov/forms/all-forms' }],
    relatedSlugs: ['us-f1-student-visa-ds160-i20-pack', 'canada-study-permit-complete-pack'],
  },
  {
    productNumber: 11,
    batch: 2,
    slug: 'us-stem-opt-i765-i983-companion-pack',
    apexSlug: 'shop-us-stem-opt-i765-i983-companion-pack',
    payhipId: '1LXUs',
    name: 'USA STEM OPT I-765 + I-983 Preparation Pack — Fillable PDF',
    price: 18.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k288ijdpb411ksd1uvi1lp0uuk1f.jpg',
    imageAlt: 'STEM graduate at laptop reviewing employment documents, real university or office setting',
    description: 'Organize STEM OPT extension facts, employer details, training-plan inputs, I-765 preparation notes and submission tracking in one fillable workbook. This product does not complete or replace Form I-765 or Form I-983 and does not determine STEM OPT eligibility. Verify current USCIS, DHS and Study in the States rules before filing.',
    deliveryLabel: '1 fillable PDF workbook',
    buyerFile: 'us-stem-opt-i765-i983-companion-pack.pdf',
    fileShopCategory: 'template',
    tags: ['STEM OPT', 'I-765', 'I-983', 'F-1 student', 'OPT extension', 'training plan', 'E-Verify employer', 'fillable PDF'],
    marketplaceCategory: 'Education',
    authorityLinks: [{ label: 'STEM OPT extension guidance — USCIS', href: 'https://www.uscis.gov/working-in-the-united-states/students-and-exchange-visitors/optional-practical-training-extension-for-stem-students-stem-opt' }, { label: 'Form I-765 — USCIS', href: 'https://www.uscis.gov/i-765' }],
    relatedSlugs: ['us-opt-i765-application-prep-pack', 'us-f1-student-visa-ds160-i20-pack'],
  },
  {
    productNumber: 12,
    batch: 2,
    slug: 'us-opt-i765-application-prep-pack',
    apexSlug: 'shop-us-opt-i765-application-prep-pack',
    payhipId: 'g7efi',
    name: 'USA F-1 OPT I-765 Application Preparation Pack — Fillable PDF',
    price: 15.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k2891sh91rso49v43l10js1fl61f.jpg',
    imageAlt: 'International university student working on laptop with graduation documents, real campus setting',
    description: 'Build an organized OPT preparation record for I-765 facts, school/SEVIS information, filing timeline, supporting documents and post-submission tracking. This workbook does not determine OPT eligibility or filing timing and is not Form I-765. Follow current USCIS and school/DSO instructions.',
    deliveryLabel: '1 fillable PDF workbook',
    buyerFile: 'us-opt-i765-application-prep-pack.pdf',
    fileShopCategory: 'template',
    tags: ['F-1 OPT', 'I-765', 'optional practical training', 'international student', 'EAD preparation', 'OPT timeline', 'USCIS checklist', 'fillable PDF'],
    marketplaceCategory: 'Education',
    authorityLinks: [{ label: 'Optional Practical Training for F-1 Students — USCIS', href: 'https://www.uscis.gov/working-in-the-united-states/students-and-exchange-visitors/optional-practical-training-opt-for-f-1-students' }, { label: 'Form I-765 — USCIS', href: 'https://www.uscis.gov/i-765' }],
    relatedSlugs: ['us-stem-opt-i765-i983-companion-pack', 'us-f1-student-visa-ds160-i20-pack'],
  },
  {
    productNumber: 13,
    batch: 2,
    slug: 'us-b1b2-visitor-visa-ds160-invitation-pack',
    apexSlug: 'shop-us-b1b2-visitor-visa-ds160-invitation-pack',
    payhipId: 'baRtH',
    name: 'USA B-1/B-2 Visitor Visa DS-160 + Trip Preparation Pack — Fillable PDF',
    price: 13.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28d9mmhda2tvlk77qknihe1a.jpg',
    imageAlt: 'Traveler at airport or desk reviewing passport and trip documents, real photography',
    description: 'Organize DS-160 facts, trip purpose, itinerary, host/invitation information where relevant, travel history and supporting-document notes before using the current U.S. visitor-visa process. An invitation letter is not represented as a universal requirement and this workbook does not predict visa approval.',
    deliveryLabel: '1 fillable PDF workbook',
    buyerFile: 'us-b1b2-visitor-visa-ds160-invitation-pack.pdf',
    fileShopCategory: 'template',
    tags: ['B1 B2 visa', 'DS-160', 'visitor visa', 'US travel', 'invitation letter', 'trip itinerary', 'visa interview', 'fillable PDF'],
    marketplaceCategory: 'Education',
    authorityLinks: [{ label: 'DS-160 information — U.S. Department of State', href: 'https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/forms/ds-160-online-nonimmigrant-visa-application.html' }, { label: 'DS-160 application — CEAC', href: 'https://ceac.state.gov/genniv/' }],
    relatedSlugs: ['us-f1-interview-home-ties-pack', 'us-f1-student-visa-ds160-i20-pack'],
  },
  {
    productNumber: 14,
    batch: 2,
    slug: 'us-f1-interview-home-ties-pack',
    apexSlug: 'shop-us-f1-interview-home-ties-pack',
    payhipId: '9Fxb4',
    name: 'USA F-1 Visa Interview + Home-Ties Preparation Pack — Fillable PDF',
    price: 12.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28ean6m1ngnfo7l68qbas1l1f.jpg',
    imageAlt: 'Student preparing for an interview or reviewing university notes, professional real-life setting',
    description: 'Prepare for an F-1 visa interview by organizing study-purpose facts, school/program reasoning, funding, prior travel and the real-life ties and plans relevant to your circumstances. The workbook does not provide scripted “winning answers” and cannot determine or guarantee a visa outcome.',
    deliveryLabel: '1 fillable PDF workbook',
    buyerFile: 'us-f1-interview-home-ties-pack.pdf',
    fileShopCategory: 'template',
    tags: ['F-1 interview', 'student visa interview', 'home ties', 'study plan', 'US student visa', 'interview preparation', 'F-1 evidence', 'fillable PDF'],
    marketplaceCategory: 'Education',
    authorityLinks: [{ label: 'Student Visa — U.S. Department of State', href: 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html' }, { label: 'DS-160 information — U.S. Department of State', href: 'https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/forms/ds-160-online-nonimmigrant-visa-application.html' }],
    relatedSlugs: ['us-f1-student-visa-ds160-i20-pack', 'us-b1b2-visitor-visa-ds160-invitation-pack'],
  },
  {
    productNumber: 15,
    batch: 2,
    slug: 'us-f1-student-visa-ds160-i20-pack',
    apexSlug: 'shop-us-f1-student-visa-ds160-i20-pack',
    payhipId: 'UuQMj',
    name: 'USA F-1 Student Visa DS-160 + I-20 Preparation Pack — Fillable PDF',
    price: 16.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28f69tv1rv61sv8s1q1run1nhl1f.jpg',
    imageAlt: 'International student studying with laptop and university documents, real campus/home study setting',
    description: 'Organize DS-160 facts, I-20/SEVIS details, school/program information, funding records, travel history and interview preparation in one fillable workbook. It is not a DS-160, I-20 or government filing service and does not determine visa eligibility or outcome.',
    deliveryLabel: '1 fillable PDF workbook',
    buyerFile: 'us-f1-student-visa-ds160-i20-pack.pdf',
    fileShopCategory: 'template',
    tags: ['F-1 visa', 'DS-160', 'I-20', 'SEVIS', 'student visa USA', 'study abroad', 'visa document organizer', 'fillable PDF'],
    marketplaceCategory: 'Education',
    authorityLinks: [{ label: 'Student Visa — U.S. Department of State', href: 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html' }, { label: 'Students and Form I-20 — DHS Study in the States', href: 'https://studyinthestates.dhs.gov/students/prepare/students-and-the-form-i-20' }, { label: 'I-901 SEVIS fee — DHS Study in the States', href: 'https://studyinthestates.dhs.gov/students/prepare/paying-the-i-901-sevis-fee' }],
    relatedSlugs: ['us-f1-interview-home-ties-pack', 'us-opt-i765-application-prep-pack'],
  },
  {
    productNumber: 16,
    batch: 2,
    slug: 'canada-study-permit-complete-pack',
    apexSlug: 'shop-canada-study-permit-complete-pack',
    payhipId: 'oOzae',
    name: 'Canada Study Permit Complete Preparation Pack — Fillable PDF',
    price: 19.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28d9o0l1uos1hpk18vb6sp1o5l1f.jpg',
    imageAlt: 'International student reviewing university and financial documents on campus or at a desk, real photography',
    description: 'A comprehensive fillable workbook for organizing study-permit facts, school/program evidence, PAL/TAL or provincial requirements where applicable, financial support, travel/history information, study-plan logic and submission tracking. Requirements change; this workbook does not determine eligibility and always defers to current IRCC/provincial instructions.',
    deliveryLabel: '1 fillable PDF workbook',
    buyerFile: 'canada-study-permit-complete-pack.pdf',
    fileShopCategory: 'template',
    tags: ['Canada study permit', 'IRCC study permit', 'PAL TAL', 'proof of funds', 'study plan', 'international student Canada', 'document checklist', 'fillable PDF'],
    marketplaceCategory: 'Education',
    authorityLinks: [{ label: 'Study permit: required documents — IRCC', href: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/get-documents.html' }, { label: 'Study permit: proof of financial support — IRCC', href: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/get-documents/financial-support.html' }, { label: 'Application forms and guides — IRCC', href: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/application/application-forms-guides.html' }],
    relatedSlugs: ['us-i134-financial-support-companion-pack', 'us-f1-student-visa-ds160-i20-pack'],
  },
  {
    productNumber: 17,
    batch: 2,
    slug: 'weekly-meal-planner-grocery-list',
    apexSlug: 'shop-weekly-meal-planner-grocery-list',
    payhipId: 'l3Cdc',
    legacyCardId: 'meal-planner',
    name: 'Weekly Meal Planner + Grocery List Workbook — Excel & Google Sheets',
    price: 8.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28e8koa1oo2197719a11jb611ri1f.jpg',
    imageAlt: 'Real kitchen table with meal planning notebook, groceries or recipe planning, no AI food collage',
    description: 'Plan seven days of meals, capture recipe ingredients and keep a categorized grocery list in one clean workbook. Includes Weekly Planner, Ingredient Log, Grocery List and Instructions sheets. No macros or fragile automation: the file is designed to stay editable in Excel and Google Sheets.',
    deliveryLabel: 'Excel workbook, Google Sheets compatible',
    buyerFile: 'weekly-meal-planner-grocery-list.xlsx',
    fileShopCategory: 'spreadsheet',
    tags: ['meal planner', 'grocery list', 'weekly meal plan', 'meal planning spreadsheet', 'grocery organizer', 'family meal planner', 'Excel template', 'Google Sheets'],
    marketplaceCategory: 'Lifestyle / Productivity',
    authorityLinks: [],
    relatedSlugs: ['90-day-guided-self-reflection-journal', '30-day-habit-wellness-tracker'],
  },
  {
    productNumber: 18,
    batch: 2,
    slug: '90-day-guided-self-reflection-journal',
    apexSlug: 'shop-90-day-guided-self-reflection-journal',
    payhipId: '87eHp',
    legacyCardId: 'reflection-journal',
    name: '90-Day Guided Self-Reflection Journal — Printable PDF',
    price: 9.99,
    imageUrl: 'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1k28f3er835g1lvj1uo4fhb1jmn1a.jpg',
    imageAlt: 'Real person journaling with notebook and coffee in calm natural light',
    description: 'A 16-page printable journal with 13 weekly themes, three guided prompts per week, writing space, one small-action commitment and a final 90-day review. Designed for reflection and planning, not diagnosis or therapy.',
    deliveryLabel: '16-page printable PDF',
    buyerFile: '90-day-guided-self-reflection-journal.pdf',
    fileShopCategory: 'guide',
    tags: ['reflection journal', '90 day journal', 'guided journal', 'self reflection prompts', 'weekly journal', 'personal growth', 'printable journal', 'PDF journal'],
    marketplaceCategory: 'Self Improvement / Lifestyle',
    authorityLinks: [],
    relatedSlugs: ['30-day-habit-wellness-tracker', 'undated-hyperlinked-digital-planner'],
  },
]
