/** Shared reader-engagement contract for every generated page and brief. */

export const EDITORIAL_CONTRACT_VERSION = '2026.08.reader-engagement.v1'

export const EDITORIAL_FORMATTING_CONTRACT = [
  `## READER-ENGAGEMENT AND EDITORIAL FORMAT CONTRACT (${EDITORIAL_CONTRACT_VERSION})`,
  '',
  'Write for a person who needs a clear next step, not for a word-count target or a crawler.',
  '1. Answer first: in the opening 1–2 paragraphs, answer the primary question in plain English. Do not begin with history, hype, or a promise.',
  '2. Build a reading path: one H1, descriptive H2s, nested H3s only when needed, and a short table of contents for long guides. Never skip heading levels for styling.',
  '3. Make it scannable: use short paragraphs (usually 1–3 sentences), informative lead sentences, bullets for sets, numbered steps for sequences, and tables only for genuine comparisons or structured facts.',
  '4. Add usable detail: explain who a step is for, what to prepare, what can change, common mistakes, and what to do next. Prefer concrete forms, agencies, documents, dates, and examples over abstract advice.',
  '5. Use deliberate visual rhythm: alternate explanatory prose with a checklist, process, comparison, example, or callout when it improves comprehension. Never add decorative lists or tables that repeat the prose.',
  '6. Make sections self-contained for answer engines: define the term, state the qualification or caveat, then explain the action. FAQ answers must answer the question directly and stand alone.',
  '7. Earn trust: distinguish official rules from practical guidance, cite authoritative primary sources with full HTTPS URLs, include a currentness note where rules change, and keep YMYL disclaimers visible.',
  '8. Link with meaning: use contextual internal links with descriptive anchor text and explain why the destination helps. Never use “click here” or inject unrelated links.',
  '9. Use calm, precise, inclusive language. No clickbait, keyword stuffing, fake urgency, invented statistics, unsupported testimonials, outcome guarantees, or manipulative “keep reading” teasers.',
  '10. Keep variation topic-led: blogs may be lighter and more narrative; procedural guides may use steps and checklists; comparisons may use a table. Apply the principles without forcing identical headings.',
  '11. KEYWORD COVERAGE (mandatory on every draft). The brief supplies two arrays:',
  '    - shortKeywords — ≥5 distinct head terms, each ≤3 words long. Each short keyword must appear at least once in the body, in context of the topic, and at most 4 times total (no stuffing).',
  '    - longTailKeywords — ≥4 distinct long-tail terms, each ≥4 words long. Each long-tail keyword must appear at least once, naturally, and at most 2 times total.',
  '    Treat each keyword from BOTH arrays as a check the scanner will enforce before ship: missing any one is a HARD blocker named missing_keyword; exceeding the cap is a HARD blocker named keyword_density_violation. The scanner also fails a draft that ships with fewer than 5 short or 4 long-tail entries.',
  '    Distribute keywords across the article: place at least one short keyword in the title slug, the first H2, and the In 60 seconds block. Place at least one long-tail keyword in the FAQ. Do not front-load every keyword in the first paragraphs.',
  '',
  '12. ANTI-WALL-OF-TEXT (mandatory): paragraphs of 1-3 sentences, each under 180 characters. No prose block may run longer than 180 chars without a visual break — split with bullets, a numbered step, a table, a callout, or a new paragraph with a bold lead. Avoid creating long blocks: the scanner flags blocks >180 chars that also have either >520 chars or ≥5 sentences. Break sections into 2-4 short paragraphs.',
  '13. CONCRETE WORKED EXAMPLE (mandatory for long-form): every page ≥1,000 words MUST include at least one concrete example with a named person, their situation, the step they took, and the result. Label it "Example:" or "Worked Example:" in its own H2 or H3. The scanner checks body text for "for example", "for instance", or "e.g." — ensure at least one such marker exists.',
  '14. SCHEMA JSON-LD (mandatory for indexable pages): Article JSON-LD `{"@type":"Article","author":{...},"datePublished":"...","description":"..."}` must be present in every page. FAQPage JSON-LD `{"@type":"FAQPage","mainEntity":[...]}` is required when the page has 4+ FAQ sections. These are rendered by the template from the article meta, keywords, and FAQ content — do not write raw schema blocks manually. The scanner will warn (not block) if either schema type is absent.',
  '',
  '## HARD FORMAT SPEC (every long-form page)',
  '',
  '- TABLE OF CONTENTS: for guides with 4+ H2 sections, open the body with exactly:',
  '    ## Table of contents',
  '    - [First section](#first-section)',
  '    - [Second section](#second-section)',
  '  Anchor = heading slug (lowercase, spaces/punctuation → hyphens). The slug',
  '  MUST exactly equal the H2 heading text written below ("Eligibility requirements"',
  '  → #eligibility-requirements). The renderer resolves these anchors; a broken',
  '  slug reads as raw markdown on the live page.',
  '',
  '- HEADING HIERARCHY: exactly one H1. ## for major sections only. ### only',
  '  nested directly under a ##. Never skip levels (H1 → H3), never use ####+.',
  '',
  '- COLLAPSIBLE SECTIONS: wrap long optional reading (fee tables, big checklists,',
  '  deep FAQ answers) in HTML <details><summary> blocks so the page stays',
  '  scannable. The renderer passes these through verbatim.',
  '',
  '- LANGUAGE LEVEL: plain English for a general reader (~8th-grade level).',
  '  Define legal and technical terms on first use, prefer sentences under 20',
  '  words, use the active voice, and address the reader directly ("you").',
  '',
  '- SCANNABILITY: paragraphs of 1–3 sentences; bullets for sets; numbered steps',
  '  for sequences; tables only for genuine comparisons; FAQ answers that stand',
  '  alone. Bold the lead phrase of long list items.',
  '',
  'FINAL READER TEST: Could a busy reader understand the answer, scan the headings, find the relevant step, verify the source, and know the next safe action without reading every word?',
].join('\n')

export function editorialBriefPromptBlock(): string {
  return [
    EDITORIAL_FORMATTING_CONTRACT,
    '',
    '## BRIEF FORMAT (required for every SEO Master Engine and GSC brief)',
    'Return a compact, skimmable brief with these labeled sections:',
    '- READER / INTENT: who is asking, what they need answered, and the safe next action.',
    '- PROMISE OF VALUE: one accurate sentence describing what the page will help the reader do; never promise an outcome.',
    '- PAGE SHAPE: recommended content type and a logical H2/H3 outline.',
    '- ANSWER-FIRST: the answer the opening should deliver in 1–2 sentences.',
    '- EVIDENCE / SOURCES: official authorities, facts to verify, and freshness risks.',
    '- ENGAGEMENT DEVICES: only the useful checklist, steps, table, example, callout, FAQ, and internal-link opportunities for this query.',
    '- COMPLIANCE NOTES: YMYL boundaries, disclaimer, uncertainty, and claims to avoid.',
    '- KEYWORD COVERAGE: the planner supplied ≥5 shortKeywords (≤3 words) and ≥4 longTailKeywords (≥4 words). The brief MUST echo them so the writer can decide where each term fits. Note any keyword that has no clean context — the writer should mark it as optional rather than force-fit.',
    'Use short labeled bullets rather than a wall of prose. Do not invent search data, fees, timelines, sources, or credentials.',
  ].join('\n')
}
