/** One canonical keyword contract for audit, editor, approval, and shipping. */
import { KEYWORD_REQUIREMENTS, partitionKeywords, isFabricatedSyntheticTerm, isUnplaceableCoverageTerm } from '@/lib/seoEngine/planner'
import { coversKeywordIntent } from '@/lib/seoFactory/contentQualityGate'
import {
  keywordSourceMap,
  keywordTermList,
  type KeywordSource,
  type KeywordTerm,
} from '@/lib/seoEngine/keywordTerms'
import {
  demandKeywordPhrases,
  keywordContractFromLists,
  parseKeywordPhrases,
  parseKeywordTerms,
  renderKeywordContractBrief,
  sanitizeBriefOutline,
  rejectFragmentKeyword,
  dropFragmentKeywords,
  dropFragmentKeywordTerms,
  isApplyTargetPrimary,
} from './keywordContractBrief'

export {
  demandKeywordPhrases,
  keywordContractFromLists,
  parseKeywordPhrases,
  parseKeywordTerms,
  renderKeywordContractBrief,
  sanitizeBriefOutline,
  rejectFragmentKeyword,
  dropFragmentKeywords,
  dropFragmentKeywordTerms,
  isApplyTargetPrimary,
}

/** Content types where a missing demand short is a ship blocker. */
const DEMAND_SHORT_BLOCKER_TYPES: ReadonlySet<string> = new Set([
  'legal_guide',
  'article',
  'regional_page',
  'regional_from',
  'regional_university',
])

const DEMAND_SHORT_WARNING_TYPES: ReadonlySet<string> = new Set([
  'blog_post',
  'blog_summary',
  'news_summary',
  'marketplace_gig',
])

/**
 * Ship/writer severity for a missing keyword. Discover analytics floors stay
 * in KEYWORD_REQUIREMENTS; this is the gate/writer contract only.
 *
 * Agent B: use this in contentQualityGate instead of hard-coding
 * `missing_short_keyword` as a blocker for every type.
 */
export function keywordSeverityForType(
  contentType: string,
  source: 'demand' | 'synthesized',
): 'blocker' | 'warning' {
  if (source === 'synthesized') return 'warning'
  const type = String(contentType || '').trim()
  if (DEMAND_SHORT_WARNING_TYPES.has(type)) return 'warning'
  if (DEMAND_SHORT_BLOCKER_TYPES.has(type) || type.startsWith('regional_')) return 'blocker'
  return type ? 'blocker' : 'warning'
}

export interface KeywordContract {
  requiredShortKeywords: string[]
  requiredLongTailKeywords: string[]
  /**
   * Per-term provenance. Terms marked `synthesized` were generated by the
   * partitioner's template backfill purely to satisfy the count floors — they
   * are not evidence of real search demand, so the quality gate reports them as
   * warnings rather than ship blockers.
   */
  shortKeywordTerms: KeywordTerm[]
  longTailKeywordTerms: KeywordTerm[]
  /** True when the partitioner had to backfill either floor. */
  backfilled: boolean
}

function dropUnplaceableTerms(terms: KeywordTerm[]): KeywordTerm[] {
  return terms.filter((entry) => !isUnplaceableCoverageTerm(entry.term))
}

function refillKeywordFloor(
  terms: KeywordTerm[],
  kind: 'short' | 'long',
  primary: string,
): KeywordTerm[] {
  const min = kind === 'short' ? KEYWORD_REQUIREMENTS.SHORT_MIN : KEYWORD_REQUIREMENTS.LONG_TAIL_MIN
  if (terms.length >= min || !String(primary || '').trim()) return terms
  const partitioned = partitionKeywords(terms.map((entry) => entry.term), primary)
  const extras = kind === 'short' ? partitioned.shortTerms : partitioned.longTailTerms
  const seen = new Set(terms.map((entry) => entry.term.toLowerCase()))
  const out = [...terms]
  for (const extra of extras) {
    if (out.length >= min) break
    const key = extra.term.toLowerCase()
    if (seen.has(key)) continue
    if (isUnplaceableCoverageTerm(extra.term)) continue
    if (rejectFragmentKeyword(extra.term, primary)) continue
    seen.add(key)
    out.push({
      term: extra.term,
      source: extra.source === 'demand' ? extra.source : 'synthesized',
    })
  }
  return out
}

function sealContract(contract: KeywordContract, primary = ''): KeywordContract {
  const shortKeywordTerms = refillKeywordFloor(
    dropFragmentKeywordTerms(dropUnplaceableTerms(contract.shortKeywordTerms), primary),
    'short',
    primary,
  )
  const longTailKeywordTerms = refillKeywordFloor(
    dropFragmentKeywordTerms(dropUnplaceableTerms(contract.longTailKeywordTerms), primary),
    'long',
    primary,
  )
  return {
    ...contract,
    requiredShortKeywords: shortKeywordTerms.map((entry) => entry.term),
    requiredLongTailKeywords: longTailKeywordTerms.map((entry) => entry.term),
    shortKeywordTerms,
    longTailKeywordTerms,
  }
}

function splitKeywordBag(raw: unknown): { short: string[]; long: string[] } {
  const short: string[] = []
  const long: string[] = []
  if (!Array.isArray(raw)) return { short, long }
  for (const item of raw) {
    const term = String(item || '').trim()
    if (!term) continue
    const words = term.split(/\s+/).filter(Boolean).length
    if (words <= 3) short.push(term)
    else if (words >= 4) long.push(term)
  }
  return { short, long }
}

/**
 * Evict uncovered SYNTHESIZED filler terms at the final gate.
 *
 * Synthesized terms exist only to satisfy the count floor — they carry no
 * demand evidence ("estimated tax payment help in 2026 explained" was never a
 * real search). Before this, an unplaced synthesized term warned forever:
 * the AI attempt could not force it in without stuffing, and no deterministic
 * pass may weave keywords. The honest closure is to DROP the filler from the
 * contract at the boundary (down to the floor), so the missing_synthesized_*
 * warning disappears with integrity instead of persisting "by design".
 *
 * Rules:
 *  - ONLY synthesized terms are evictable; demand terms never are.
 *  - Coverage uses the same strict low-passage intent match the gate uses
 *    (`coversKeywordIntent`), so document-wide scattering never counts.
 *  - Fabrication-marker filler ("requirements for a …", "…in 2026 explained",
 *    "…checklist and timeline") is evicted FIRST — it is unplaceable by
 *    construction.
 *  - The arrays never drop below the count floors (removing the floor would
 *    re-introduce insufficient_* blockers).
 */
export function pruneUnplaceableSynthesizedKeywords(input: {
  content: string
  primaryKeyword?: string | null
  requiredShortKeywords?: unknown
  requiredLongTailKeywords?: unknown
  shortKeywordTerms?: unknown
  longTailKeywordTerms?: unknown
}): {
  requiredShortKeywords: string[]
  requiredLongTailKeywords: string[]
  shortKeywordTerms: KeywordTerm[]
  longTailKeywordTerms: KeywordTerm[]
  pruned: number
  prunedTerms: string[]
} {
  const body = String(input.content || '').toLowerCase()
  const covered = (term: string) => coversKeywordIntent(body, term)
  // Fresh NATURAL filler from the current (tightened) templates — used to
  // replace legacy fabrication-marker terms 1:1 while holding the floor.
  const freshTemplates = (() => {
    const primary = String(input.primaryKeyword || '').trim()
    if (!primary) return new Map<string, KeywordTerm>()
    const partitioned = partitionKeywords([], primary)
    const map = new Map<string, KeywordTerm>()
    for (const t of [...partitioned.shortTerms, ...partitioned.longTailTerms]) {
      if (t.source === 'synthesized' && !isFabricatedSyntheticTerm(t.term) && !map.has(t.term.toLowerCase())) {
        map.set(t.term.toLowerCase(), t)
      }
    }
    return map
  })()
  const terms = (raw: unknown, provenance: unknown, min: number, kind: 'short' | 'long'): {
    list: KeywordTerm[]; pruned: number; prunedTerms: string[]
  } => {
    const arr = Array.isArray(raw) ? raw.map(String).map((t) => t.trim()).filter(Boolean) : []
    const known = keywordSourceMap(
      keywordTermList(Array.isArray(provenance) ? (provenance as Array<string | KeywordTerm>) : []),
    )
    const withSource = arr.map((term) => {
      const source = known.get(term.toLowerCase())
      if (source) return { term, source }
      return { term, source: (isFabricatedSyntheticTerm(term) ? 'synthesized' : 'demand') as KeywordSource }
    })
    const evictable = withSource.filter((entry) => entry.source === 'synthesized' && !covered(entry.term))
    let list = withSource
    let pruned = 0
    let prunedTerms: string[] = []
    if (evictable.length) {
      // Fabrication markers first, then the rest.
      const ordered = [...evictable].sort((a, b) => Number(isFabricatedSyntheticTerm(b.term)) - Number(isFabricatedSyntheticTerm(a.term)))
      for (const entry of ordered) {
        const room = list.length - min
        if (room <= 0) break
        list = list.filter((k) => k.term !== entry.term)
        pruned++
        prunedTerms.push(entry.term)
      }
    }
    // Final closure: legacy fabrication-MARKER terms still resident (because
    // the floor left no room to evict them) are swapped 1:1 with fresh,
    // grammatical template terms — same count, no junk left in the contract.
    const candidates = [...freshTemplates.values()]
    let cursor = 0
    list = list.map((entry) => {
      if (entry.source !== 'synthesized' || !(isFabricatedSyntheticTerm(entry.term) || isUnplaceableCoverageTerm(entry.term))) return entry
      while (cursor < candidates.length) {
        const candidate = candidates[cursor++]
        if (list.some((k) => k.term.toLowerCase() === candidate.term.toLowerCase())) continue
        if (kind === 'short' && candidate.term.split(/\s+/).length > 3) continue
        if (kind === 'long' && candidate.term.split(/\s+/).length < 4) continue
        prunedTerms.push(entry.term)
        return { term: candidate.term, source: 'synthesized' as KeywordSource }
      }
      return entry
    })
    return { list, pruned, prunedTerms }
  }

  const short = terms(input.requiredShortKeywords, input.shortKeywordTerms, KEYWORD_REQUIREMENTS.SHORT_MIN, 'short')
  const longTail = terms(input.requiredLongTailKeywords, input.longTailKeywordTerms, KEYWORD_REQUIREMENTS.LONG_TAIL_MIN, 'long')
  return {
    requiredShortKeywords: short.list.map((e) => e.term),
    requiredLongTailKeywords: longTail.list.map((e) => e.term),
    shortKeywordTerms: short.list,
    longTailKeywordTerms: longTail.list,
    pruned: short.pruned + longTail.pruned,
    prunedTerms: [...short.prunedTerms, ...longTail.prunedTerms],
  }
}

export function resolveKeywordContract(input: {
  primaryKeyword?: string | null
  topic?: string | null
  requiredShortKeywords?: unknown
  requiredLongTailKeywords?: unknown
  /** Optional persisted provenance so a re-audit does not lose it. */
  shortKeywordTerms?: unknown
  longTailKeywordTerms?: unknown
}): KeywordContract {
  const primary = String(input.primaryKeyword || input.topic || '').trim()
  // Legacy jobs persisted only flat arrays. Recover the provenance of exact
  // partitioner templates from the primary term so those old synthetic terms
  // do not become permanent hard blockers merely because metadata predates
  // the provenance fields.
  const legacyTemplates = partitionKeywords([], primary)
  const legacySynthetic = keywordSourceMap([
    ...legacyTemplates.shortTerms,
    ...legacyTemplates.longTailTerms,
  ].filter((entry) => entry.source === 'synthesized'))
  const asTerms = (raw: unknown, persisted: unknown): KeywordTerm[] => {
    const list = Array.isArray(raw) ? raw.map(String).map((t) => t.trim()).filter(Boolean) : []
    // Reattach provenance for terms whose source was persisted alongside them.
    const known = keywordSourceMap(
      keywordTermList(Array.isArray(persisted) ? (persisted as Array<string | KeywordTerm>) : []),
    )
    return list.map((term) => {
      const lower = term.toLowerCase()
      const persistedSource = known.get(lower)
      if (persistedSource) return { term, source: persistedSource }
      const legacySyntheticSource = legacySynthetic.get(lower)
      // Recover mill long-tails and unplaceable/fabricated strings so old
      // queue rows do not become demand blockers. Do NOT recover short
      // windows of the primary ("visa fee") — those are often real
      // caller-supplied demand that happens to equal a contiguous slice.
      if (
        legacySyntheticSource
        && (isFabricatedSyntheticTerm(term) || isUnplaceableCoverageTerm(term) || term.split(/\s+/).length >= 4)
      ) {
        return { term, source: legacySyntheticSource }
      }
      // Legacy jobs persisted flat keyword arrays BEFORE provenance existed.
      // Terms that match the partitioner's FABRICATED template markers were
      // machine backfill, never real demand — typing them 'demand' would turn
      // every old queue draft into a permanent missing_*_keyword blocker after
      // a template change (the fabrications no longer round-trip).
      if (isFabricatedSyntheticTerm(term) || isUnplaceableCoverageTerm(term)) {
        return { term, source: 'synthesized' as KeywordSource }
      }
      return { term, source: 'demand' as KeywordSource }
    })
  }

  const short = dropFragmentKeywordTerms(asTerms(input.requiredShortKeywords, input.shortKeywordTerms), primary)
  const longTail = dropFragmentKeywordTerms(asTerms(input.requiredLongTailKeywords, input.longTailKeywordTerms), primary)
  if (short.length >= KEYWORD_REQUIREMENTS.SHORT_MIN && longTail.length >= KEYWORD_REQUIREMENTS.LONG_TAIL_MIN) {
    return sealContract({
      requiredShortKeywords: short.map((entry) => entry.term),
      requiredLongTailKeywords: longTail.map((entry) => entry.term),
      shortKeywordTerms: short,
      longTailKeywordTerms: longTail,
      backfilled: false,
    }, primary)
  }

  const partition = partitionKeywords(
    [...short, ...longTail].map((entry) => entry.term),
    primary,
  )
  // Terms the caller already supplied stay `demand` even if the partitioner
  // re-emits them; only genuinely new filler is marked `synthesized`. Terms
  // carrying a legacy fabrication marker stay synthesized even when
  // caller-supplied — the old templates are gone, so there is no demand
  // evidence that could ever re-classify them.
  const supplied = keywordSourceMap([...short, ...longTail])
  const withProvenance = (terms: KeywordTerm[]): KeywordTerm[] => terms.map(({ term, source }) => ({
    term,
    source: isFabricatedSyntheticTerm(term) || isUnplaceableCoverageTerm(term)
      ? ('synthesized' as KeywordSource)
      : (supplied.get(term.toLowerCase()) ?? source),
  }))
  const shortTerms = dropFragmentKeywordTerms(withProvenance(partition.shortTerms), primary)
  const longTailTerms = dropFragmentKeywordTerms(withProvenance(partition.longTailTerms), primary)

  return sealContract({
    requiredShortKeywords: shortTerms.map((entry) => entry.term),
    requiredLongTailKeywords: longTailTerms.map((entry) => entry.term),
    shortKeywordTerms: shortTerms,
    longTailKeywordTerms: longTailTerms,
    backfilled: true,
  }, primary)
}

/**
 * Single hop from a brief / generate payload to the contract the drafter,
 * Harper, audit, and ship all share. If the brief already met the floors,
 * this MUST NOT re-run the partitioner and invent extra coverage terms.
 */
export function keywordContractForDraft(input: {
  primaryKeyword?: string | null
  topic?: string | null
  keywords?: unknown
  requiredShortKeywords?: unknown
  requiredLongTailKeywords?: unknown
  shortKeywordTerms?: unknown
  longTailKeywordTerms?: unknown
}): KeywordContract {
  const providedShort = Array.isArray(input.requiredShortKeywords)
    ? input.requiredShortKeywords.map(String).map((t) => t.trim()).filter(Boolean)
    : []
  const providedLong = Array.isArray(input.requiredLongTailKeywords)
    ? input.requiredLongTailKeywords.map(String).map((t) => t.trim()).filter(Boolean)
    : []
  const bag = (!providedShort.length && !providedLong.length)
    ? splitKeywordBag(input.keywords)
    : { short: providedShort, long: providedLong }
  const primary = String(input.primaryKeyword || input.topic || '').trim()
  return resolveKeywordContract({
    primaryKeyword: input.primaryKeyword,
    topic: input.topic,
    requiredShortKeywords: dropFragmentKeywords(bag.short, primary),
    requiredLongTailKeywords: dropFragmentKeywords(bag.long, primary),
    shortKeywordTerms: input.shortKeywordTerms,
    longTailKeywordTerms: input.longTailKeywordTerms,
  })
}
