/** One canonical keyword contract for audit, editor, approval, and shipping. */
import { KEYWORD_REQUIREMENTS, partitionKeywords } from '@/lib/seoEngine/planner'
import {
  keywordSourceMap,
  keywordTermList,
  type KeywordSource,
  type KeywordTerm,
} from '@/lib/seoEngine/keywordTerms'

export interface KeywordContract {
  requiredShortKeywords: string[]
  requiredLongTailKeywords: string[]
  /**
   * Per-term provenance. Terms marked `synthesized` were generated by the
   * partitioner's template backfill purely to satisfy the count floors — they
   * are not evidence of real search demand, so the quality gate reports them as
   * warnings rather than ship blockers.
   */
  shortKeywordTerms: KeywordTerm[]
  longTailKeywordTerms: KeywordTerm[]
  /** True when the partitioner had to backfill either floor. */
  backfilled: boolean
}

export function resolveKeywordContract(input: {
  primaryKeyword?: string | null
  topic?: string | null
  requiredShortKeywords?: unknown
  requiredLongTailKeywords?: unknown
  /** Optional persisted provenance so a re-audit does not lose it. */
  shortKeywordTerms?: unknown
  longTailKeywordTerms?: unknown
}): KeywordContract {
  const primary = String(input.primaryKeyword || input.topic || '').trim()
  // Legacy jobs persisted only flat arrays. Recover the provenance of exact
  // partitioner templates from the primary term so those old synthetic terms
  // do not become permanent hard blockers merely because metadata predates
  // the provenance fields.
  const legacySynthetic = keywordSourceMap([
    ...partitionKeywords([], primary).shortTerms,
    ...partitionKeywords([], primary).longTailTerms,
  ].filter((entry) => entry.source === 'synthesized'))
  const asTerms = (raw: unknown, persisted: unknown): KeywordTerm[] => {
    const list = Array.isArray(raw) ? raw.map(String).map((t) => t.trim()).filter(Boolean) : []
    // Reattach provenance for terms whose source was persisted alongside them.
    const known = keywordSourceMap(
      keywordTermList(Array.isArray(persisted) ? (persisted as Array<string | KeywordTerm>) : []),
    )
    return list.map((term) => ({
      term,
      source: (known.get(term.toLowerCase()) ?? legacySynthetic.get(term.toLowerCase()) ?? 'demand') as KeywordSource,
    }))
  }

  const short = asTerms(input.requiredShortKeywords, input.shortKeywordTerms)
  const longTail = asTerms(input.requiredLongTailKeywords, input.longTailKeywordTerms)
  if (short.length >= KEYWORD_REQUIREMENTS.SHORT_MIN && longTail.length >= KEYWORD_REQUIREMENTS.LONG_TAIL_MIN) {
    return {
      requiredShortKeywords: short.map((entry) => entry.term),
      requiredLongTailKeywords: longTail.map((entry) => entry.term),
      shortKeywordTerms: short,
      longTailKeywordTerms: longTail,
      backfilled: false,
    }
  }

  const partition = partitionKeywords(
    [...short, ...longTail].map((entry) => entry.term),
    primary,
  )
  // Terms the caller already supplied stay `demand` even if the partitioner
  // re-emits them; only genuinely new filler is marked `synthesized`.
  const supplied = keywordSourceMap([...short, ...longTail])
  const withProvenance = (terms: KeywordTerm[]): KeywordTerm[] => terms.map(({ term, source }) => ({
    term,
    source: supplied.get(term.toLowerCase()) ?? source,
  }))
  const shortTerms = withProvenance(partition.shortTerms)
  const longTailTerms = withProvenance(partition.longTailTerms)

  return {
    requiredShortKeywords: shortTerms.map((entry) => entry.term),
    requiredLongTailKeywords: longTailTerms.map((entry) => entry.term),
    shortKeywordTerms: shortTerms,
    longTailKeywordTerms: longTailTerms,
    backfilled: true,
  }
}
