/**
 * House visual register for per-page OG cards.
 *
 * StyleGAN split without a GAN: content = title + country + one artefact;
 * style = YouSafe/MyCaseworks desk palette. No faces, no passports, no
 * fake stamps, no Getty family-at-the-airport. Social crawlers get PNG via
 * a colocated Next.js `opengraph-image.tsx` (Satori at build/request time).
 */

export type OgBrand = 'mycaseworks' | 'yousafe'

export type OgCardSpec = {
  brand: OgBrand
  kicker: string
  title: string
  artefact: string
  footer: string
  bg: string
  fg: string
  mute: string
  gold: string
}

const COUNTRY: Record<string, string> = {
  us: 'United States',
  uk: 'United Kingdom',
  ca: 'Canada',
  au: 'Australia',
}

const ARTEFACT_RE =
  /\b((?:Form\s+)?I-\d+[A-Z]?|IMM\s*\d+|CAS|CoE|SEVIS|UKVI|USCIS|IRCC|Home Affairs)\b/i

export function ogImageFilePath(pageFilePath: string): string | null {
  const p = String(pageFilePath || '')
  if (!/\/page\.tsx$/.test(p)) return null
  return p.replace(/\/page\.tsx$/, '/opengraph-image.tsx')
}

export function ogImagePublicPath(pageFilePath: string): string | null {
  const file = ogImageFilePath(pageFilePath)
  if (!file) return null
  const trimmed = file.replace(/^landing-page\//, '').replace(/^app\//, '')
  return `/${trimmed.replace(/\/opengraph-image\.tsx$/, '/opengraph-image')}`
}

export function extractOgArtefact(content: string, primaryKeyword?: string): string {
  const hit = String(content || '').match(ARTEFACT_RE)
  if (hit) return hit[1].replace(/\s+/g, ' ').trim()
  const kw = String(primaryKeyword || '').trim()
  if (kw && kw.length <= 48) return kw
  return ''
}

export function buildOgCardSpec(opts: {
  title: string
  region?: string | null
  contentType?: string | null
  primaryKeyword?: string | null
  content?: string | null
  filePath?: string | null
}): OgCardSpec {
  const blog = /blog/i.test(String(opts.contentType || '')) || /\/blog\//.test(String(opts.filePath || ''))
  const region = String(opts.region || '')
    .toLowerCase()
    .replace(/[^a-z]/g, '')
    .slice(0, 2)
  const country = COUNTRY[region] || ''
  const title = String(opts.title || opts.primaryKeyword || 'Guide')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 110)
  const artefact = extractOgArtefact(String(opts.content || ''), opts.primaryKeyword || undefined)
  if (blog) {
    return {
      brand: 'yousafe',
      kicker: country ? `${country} · Essay` : 'YouSafe · Essay',
      title,
      artefact,
      footer: 'YouSafe Consultancy · educational only',
      bg: '#F4EFE6',
      fg: '#0F1C2E',
      mute: '#5C6B7A',
      gold: '#8A6A3D',
    }
  }
  return {
    brand: 'mycaseworks',
    kicker: country ? `${country} · Guide` : 'MyCaseworks · Guide',
    title,
    artefact,
    footer: 'MyCaseworks · educational only, not legal advice',
    bg: '#0F1C2E',
    fg: '#F4EFE6',
    mute: '#C5D0DA',
    gold: '#C4A574',
  }
}

/** Colocated Next.js OG module. Title/artefact are JSON-stringified into JSX text. */
export function renderOpenGraphImageModule(spec: OgCardSpec): string {
  return `// Generated by SEO Factory — per-page OG card. Do not hand-paint people or stamps.
import { ImageResponse } from "next/og";

export const alt = ${JSON.stringify(spec.title)};
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpenGraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: ${JSON.stringify(spec.bg)},
          color: ${JSON.stringify(spec.fg)},
          padding: "64px 72px",
        }}
      >
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{
              fontSize: 22,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              color: ${JSON.stringify(spec.gold)},
            }}
          >
            ${escapeJsx(spec.kicker)}
          </div>
          <div
            style={{
              marginTop: 28,
              fontSize: 54,
              lineHeight: 1.15,
              fontWeight: 600,
              maxWidth: 980,
            }}
          >
            ${escapeJsx(spec.title)}
          </div>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          ${
            spec.artefact
              ? `<div style={{ fontSize: 24, color: ${JSON.stringify(spec.mute)} }}>${escapeJsx(spec.artefact)}</div>`
              : ''
          }
          <div style={{ fontSize: 20, color: ${JSON.stringify(spec.gold)} }}>${escapeJsx(spec.footer)}</div>
        </div>
      </div>
    ),
    { width: 1200, height: 630 },
  );
}
`
}

function escapeJsx(s: string): string {
  return String(s || '')
    .replace(/&/g, '\u0026amp;')
    .replace(/</g, '\u0026lt;')
    .replace(/>/g, '\u0026gt;')
    .replace(/\{/g, '&#123;')
    .replace(/\}/g, '&#125;')
}

export function renderOgImageFile(opts: {
  planFilePath: string
  title: string
  region?: string | null
  contentType?: string | null
  primaryKeyword?: string | null
  content?: string | null
}): { filePath: string; fileContent: string; publicPath: string } | null {
  const filePath = ogImageFilePath(opts.planFilePath)
  const publicPath = ogImagePublicPath(opts.planFilePath)
  if (!filePath || !publicPath) return null
  const spec = buildOgCardSpec({
    title: opts.title,
    region: opts.region,
    contentType: opts.contentType,
    primaryKeyword: opts.primaryKeyword,
    content: opts.content,
    filePath: opts.planFilePath,
  })
  return { filePath, publicPath, fileContent: renderOpenGraphImageModule(spec) }
}
