/**
 * Render repo-specific file content for SEO Factory ships.
 * Caseworks → full Next.js page.tsx using ArticleLayout.
 * Other hosts → markdown/MDX with YAML front matter.
 */

import type { OwnerPlan } from './ownership'

function escapeTs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function stripFrontMatter(content: string): { fm: Record<string, string>; body: string } {
  const m = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/)
  if (!m) return { fm: {}, body: content }
  const fm: Record<string, string> = {}
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':')
    if (i < 0) continue
    const k = line.slice(0, i).trim()
    let v = line.slice(i + 1).trim()
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1)
    fm[k] = v
  }
  return { fm, body: m[2] }
}

/** Convert markdown body to simple JSX fragment strings for ArticleLayout children. */
function markdownToJsx(body: string): string {
  const lines = body.split('\n')
  const out: string[] = []
  let inList = false
  let para: string[] = []

  const flushPara = () => {
    if (!para.length) return
    const text = para.join(' ').replace(/"/g, '&quot;')
    // basic bold/italic/link leave as text for safety
    out.push(`      <p>${escapeJsxText(para.join(' '))}</p>`)
    para = []
  }

  for (const raw of lines) {
    const line = raw.trimEnd()
    if (!line.trim()) {
      flushPara()
      if (inList) {
        out.push('      </ul>')
        inList = false
      }
      continue
    }
    if (line.startsWith('## ')) {
      flushPara()
      if (inList) {
        out.push('      </ul>')
        inList = false
      }
      const id = line
        .slice(3)
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
      out.push(`      <h2 id="${id}">${escapeJsxText(line.slice(3))}</h2>`)
      continue
    }
    if (line.startsWith('### ')) {
      flushPara()
      out.push(`      <h3>${escapeJsxText(line.slice(4))}</h3>`)
      continue
    }
    if (line.startsWith('- ') || line.startsWith('* ')) {
      flushPara()
      if (!inList) {
        out.push('      <ul>')
        inList = true
      }
      out.push(`        <li>${escapeJsxText(line.slice(2))}</li>`)
      continue
    }
    if (line.startsWith('```')) {
      flushPara()
      continue // skip fenced blocks in JSX conversion
    }
    para.push(line.trim())
  }
  flushPara()
  if (inList) out.push('      </ul>')
  return out.join('\n')
}

function escapeJsxText(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\{/g, '&#123;')
    .replace(/\}/g, '&#125;')
}

function renderCaseworksPage(opts: {
  plan: OwnerPlan
  content: string
  title: string
  region: string
  primaryKeyword: string
  indexable: boolean
  canonicalUrl: string
}): string {
  const { fm, body } = stripFrontMatter(opts.content)
  const title = fm.title || opts.title
  const description =
    fm.description ||
    fm.metaDescription ||
    `${title} — practical guide for international students and immigrants. Editorial only; not legal advice.`
  const slug =
    opts.plan.filePath
      .split('/')
      .filter((p) => p && p !== 'page.tsx' && p !== 'app')
      .slice(-1)[0] || 'guide'
  const country = (opts.region || 'us').toLowerCase() === 'compare' ? 'us' : (opts.region || 'us').toLowerCase()
  const today = new Date().toISOString().slice(0, 10)
  const robots = opts.indexable ? '{ index: true, follow: true }' : '{ index: false, follow: true }'
  const jsxBody = markdownToJsx(body)
  const keyword = opts.primaryKeyword || fm.primaryKeyword || title

  return `// Generated by SEO Factory — do not hand-edit without review
import type { Metadata } from "next";
import { ArticleLayout } from "@/components/article/ArticleLayout";
import { UpdatedStamp } from "@/components/article/UpdatedStamp";
import { Tldr } from "@/components/article/Tldr";
import { CTAPanel } from "@/components/article/CTAPanel";
import { Disclaimer } from "@/components/article/Disclaimer";
import type { ArticleMeta, RelatedRef, SourceRef } from "@/lib/article-types";

const meta: ArticleMeta = {
  slug: ${JSON.stringify(slug)},
  country: ${JSON.stringify(country)},
  topic: "immigration",
  title: ${JSON.stringify(title)},
  primaryKeyword: ${JSON.stringify(keyword)},
  publishedDate: ${JSON.stringify(today)},
  updatedDate: ${JSON.stringify(today)},
  author: { name: "MyCaseworks Editorial", firm: "MyCaseworks", url: "https://legal.yousafeconsultancy.com/about/" },
  reviewer: { name: "MyCaseworks Editorial", firm: "MyCaseworks", url: "https://legal.yousafeconsultancy.com/about/" },
  reviewStatus: "editorial-only",
  hero: { eyebrow: ${JSON.stringify(country.toUpperCase() + ' · Guide')}, kicker: "SEO Factory" },
  ctaTarget: ${JSON.stringify(`/intake?country=${country}&topic=immigration`)},
  faqSchema: true,
};

const related: RelatedRef[] = [];
const sources: SourceRef[] = [];

export const metadata: Metadata = {
  title: ${JSON.stringify(title.slice(0, 60))},
  description: ${JSON.stringify(description.slice(0, 160))},
  keywords: [${JSON.stringify(keyword)}],
  alternates: { canonical: ${JSON.stringify(opts.canonicalUrl)} },
  robots: ${robots},
  openGraph: {
    siteName: "MyCaseworks",
    title: ${JSON.stringify(title.slice(0, 60))},
    description: ${JSON.stringify(description.slice(0, 160))},
    url: ${JSON.stringify(opts.canonicalUrl)},
    type: "article",
    publishedTime: ${JSON.stringify(today)},
    modifiedTime: ${JSON.stringify(today)},
  },
  twitter: { card: "summary_large_image" },
};

export default function Page() {
  return (
    <ArticleLayout meta={meta} related={related} sources={sources}>
      <UpdatedStamp date={${JSON.stringify(today)}} reviewer="MyCaseworks Editorial" />
      <Tldr title="In 60 seconds">
        <p>This guide was generated by the SEO Factory from live Search Console demand. Verify every official rule against primary government sources before relying on it.</p>
      </Tldr>
${jsxBody}
      <CTAPanel
        title="Need a document review?"
        body="MyCaseworks provides document preparation and attorney-matching — not a substitute for licensed legal advice."
      />
      <Disclaimer />
    </ArticleLayout>
  );
}
`
}

export function renderTargetFile(opts: {
  plan: OwnerPlan
  content: string
  title: string
  region: string
  contentType: string
  primaryKeyword: string
  indexable: boolean
  canonicalUrl: string
}): { filePath: string; fileContent: string } {
  const filePath = opts.plan.filePath

  if (opts.plan.repo === 'caseworks' && filePath.endsWith('page.tsx')) {
    return {
      filePath,
      fileContent: renderCaseworksPage(opts),
    }
  }

  // Markdown / MDX for portal catalogue and regional content folders
  const { fm, body } = stripFrontMatter(opts.content)
  const title = fm.title || opts.title
  const description = fm.description || `${title} — YouSafe Consultancy`
  const robots = opts.indexable ? 'index,follow' : 'noindex,follow'
  const front = [
    '---',
    `title: ${JSON.stringify(title)}`,
    `description: ${JSON.stringify(description.slice(0, 160))}`,
    `primaryKeyword: ${JSON.stringify(opts.primaryKeyword)}`,
    `canonical: ${JSON.stringify(opts.canonicalUrl)}`,
    `robots: ${robots}`,
    `ownerHost: ${opts.plan.host}`,
    `generatedBy: seo-factory`,
    `date: ${new Date().toISOString().slice(0, 10)}`,
    '---',
    '',
  ].join('\n')

  return {
    filePath,
    fileContent: front + body.trim() + '\n',
  }
}
