-- P4 destructive cannibalization decision ledger (additive).
--
-- Evidence, not history rewriting: every approval / execution / PR event is a
-- NEW row. The append-only trigger below refuses UPDATE and DELETE outright, so
-- an approved decision can never be silently edited into a different winner,
-- loser set, or evidence hash after the fact.
--
-- Deliberately NO unique(cluster_id): a cluster accumulates one immutable row
-- per attempt (approved -> pr_opened -> failed -> superseded), which is the
-- audit trail the pre-P4 `cannibal_merges` upsert destroyed.

create table if not exists public.seo_cannibal_decisions (
  id uuid primary key default gen_random_uuid(),
  cluster_id text not null check (nullif(trim(cluster_id), '') is not null),
  term text not null check (nullif(trim(term), '') is not null),
  attempt bigint generated by default as identity,
  status text not null check (status in ('approved','executing','pr_opened','rejected','failed','superseded')),
  evidence_source text not null check (evidence_source in ('gsc_live','persisted_qualified_gsc')),
  evidence_hash text not null check (nullif(trim(evidence_hash), '') is not null),
  evidence_window jsonb not null,
  evidence jsonb not null,
  competitors jsonb not null,
  winner_url text not null check (nullif(trim(winner_url), '') is not null),
  owner_registry_row_id integer not null check (owner_registry_row_id > 0),
  loser_actions jsonb not null,
  rollback jsonb not null,
  decided_by text not null check (nullif(trim(decided_by), '') is not null),
  decided_at timestamptz not null,
  pr_url text,
  pr_number integer,
  created_at timestamptz not null default now()
);

-- Append-only enforcement (idempotent): the ledger is a history, never a row to
-- be re-pointed. Service-role code inserts; nothing updates or deletes.
create or replace function public.seo_cannibal_decisions_append_only()
returns trigger
language plpgsql
as $$
begin
  raise exception 'seo_cannibal_decisions is append-only; insert a new status row instead of %', tg_op;
end;
$$;

drop trigger if exists seo_cannibal_decisions_no_update on public.seo_cannibal_decisions;
create trigger seo_cannibal_decisions_no_update
  before update or delete on public.seo_cannibal_decisions
  for each row execute function public.seo_cannibal_decisions_append_only();

create index if not exists seo_cannibal_decisions_cluster_created_idx
  on public.seo_cannibal_decisions (cluster_id, created_at desc);
create index if not exists seo_cannibal_decisions_status_created_idx
  on public.seo_cannibal_decisions (status, created_at desc);
create index if not exists seo_cannibal_decisions_hash_idx
  on public.seo_cannibal_decisions (evidence_hash);

alter table public.seo_cannibal_decisions enable row level security;

do $$
begin
  execute 'drop policy if exists "Service role full access" on public.seo_cannibal_decisions';
  execute 'create policy "Service role full access" on public.seo_cannibal_decisions for all to service_role using (true) with check (true)';
end
$$;

-- Service-role-only: no anon/authenticated read, write, or history mutation.
revoke all privileges on table public.seo_cannibal_decisions from public, anon, authenticated;
grant all privileges on table public.seo_cannibal_decisions to service_role;

comment on table public.seo_cannibal_decisions is
  'P4 append-only destructive cannibalization decision ledger. One immutable row per decision attempt; a cluster is never overwritten in place.';
comment on column public.seo_cannibal_decisions.evidence_hash is
  'SHA-256 of the canonical decision evidence; re-verified before any Git mutation.';
comment on column public.seo_cannibal_decisions.rollback is
  'Recorded repo/path/sha snapshot plus restore instructions. A mismatch against live main fails the executor closed before any write.';
